export const PAGES_TEMPLATE_FILES = Object.freeze([
  "coi-bootstrap.js",
  "coi-direct.js",
  "coi-serviceworker.js",
  "index.html",
  "legal.html",
]);

export const PAGES_HARNESS_FILES = Object.freeze([
  "analytics.mjs",
  "assets/brand/project-new-shoes-apple-touch.png",
  "assets/brand/project-new-shoes-icon-192.png",
  "assets/brand/project-new-shoes-icon-512.png",
  "assets/brand/project-new-shoes.ico",
  "assets/launcher-logo.webp",
  "assets/zeroh-autumn-offensive-1440p.webp",
  "assets/zeroh-autumn-offensive-swatch.webp",
  "assets/zeroh-azul-armada-1440p.webp",
  "assets/zeroh-azul-armada-swatch.webp",
  "assets/zeroh-bliss-at-war-4k.webp",
  "assets/zeroh-bliss-at-war-swatch.webp",
  "assets/zeroh-command-desert.webp",
  "assets/zeroh-red-moon-front-1440p.webp",
  "assets/zeroh-red-moon-front-swatch.webp",
  "bink_runtime.mjs",
  "bridge.js",
  "camera-zoom-config.mjs",
  "d3d8_executor.mjs",
  "device-transfer-protocol.mjs",
  "engine_realm_boot.mjs",
  "gdi_executor.mjs",
  "harness.css",
  "io_worker.mjs",
  "issue-recorder.mjs",
  "launcher-archive-specs.js",
  "launcher-asset-manager.mjs",
  "launcher-asset-worker.js",
  "launcher-build-info.js",
  "launcher-desktop-apps.js",
  "launcher-device-transfer.mjs",
  "launcher-entry.mjs",
  "launcher-hardware-info.js",
  "launcher-os-shutdown.mjs",
  "launcher-retail-presentation.mjs",
  "launcher-runtime.css",
  "launcher.css",
  "launcher.js",
  "manifest.webmanifest",
  "multiplayer_identity.mjs",
  "multiplayer_launch_policy.mjs",
  "network-diagnostics.mjs",
  "opfs_realm_files.mjs",
  "play.mjs",
  "replay-file-store.mjs",
  "runtime-shutdown-sequence.mjs",
  "save-persistence-coordinator.mjs",
  "shader-tier-config.mjs",
  "udp_realm_bridge.mjs",
  "transfer-user-data-store.mjs",
  "vendor/pako-LICENSE.txt",
  "vendor/pako.es5.min.js",
  "vendor/noble-secp256k1-LICENSE.txt",
  "vendor/primer-octicons-LICENSE.txt",
  "vendor/trystero-LICENSE.txt",
  "vendor/trystero-nostr.min.mjs",
  "webrtc-udp-endpoint.mjs",
]);

export const PAGES_RUNTIME_FILES = Object.freeze([
  "cnc-port.js",
  "cnc-port.wasm",
  "cnc-port.worker.js",
]);

export const PAGES_ROOT_LAUNCHER_FILES = Object.freeze([
  "launcher.html",
  "manifest.webmanifest",
]);

export const PAGES_OUTPUT_FILES = Object.freeze([
  ".nojekyll",
  "LICENSE.md",
  ...PAGES_TEMPLATE_FILES,
  ...PAGES_ROOT_LAUNCHER_FILES,
  ...PAGES_HARNESS_FILES.map((name) => `harness/${name}`),
  "harness/build-info.json",
  "harness/play.html",
  ...PAGES_RUNTIME_FILES.map((name) => `dist-threaded-release/${name}`),
].sort());
