#!/usr/bin/env node
// verify_bink_browser_video_outputs.mjs
//
// Verifies the browser-decodable sidecar manifest emitted by
// `transcode_bink_video_payloads.mjs`.
//
// The original BIK payloads remain the source of truth. This verifier checks
// that the generated WebM outputs and manifest preserve the pinned source BIK
// metadata and, when ffprobe is available, that the real output media carries
// the expected browser codecs, dimensions, frame count, and audio streams.
// With `--allow-missing`, absent outputs are reported but tolerated so the
// script remains useful before the transcode step has run.

import { open, readFile, stat } from "node:fs/promises";
import { spawn } from "node:child_process";
import { basename, dirname, isAbsolute, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const toolDir = dirname(fileURLToPath(import.meta.url));
const wasmRoot = resolve(toolDir, "..");

const DEFAULT_OUTPUT_DIR = resolve(wasmRoot, "artifacts/browser-video/bink");
const DEFAULT_MANIFEST_NAME = "bink-browser-video-manifest.json";
const SOURCE_ASSETS_DIR = resolve(wasmRoot, "artifacts/real-assets");

const PAYLOAD_FILES = ["GC_Background.bik", "VS_small.bik"];
const MANIFEST_SCHEMA = "cnc-zh-bink-browser-video-manifest/v1";
const SOURCE_TAG = "WebAssembly/tools/verify_bink_browser_video_outputs.mjs";

const PINNED_FACTS = {
  "GC_Background.bik": {
    name: "GC_Background",
    sourceSize: 149700,
    sourceSignature: "BIKi",
    sourceFormat: "bink",
    sourceVideoCodec: "binkvideo",
    sourceAudioCodecs: ["binkaudio_dct"],
    frames: 180,
    width: 800,
    height: 600,
    fpsNum: 30,
    fpsDen: 1,
    sourceDurationSeconds: 6,
    outputFile: "GC_Background.webm",
    outputVideoCodec: "vp9",
    outputAudioCodecs: ["opus"],
  },
  "VS_small.bik": {
    name: "VS_small",
    sourceSize: 310128,
    sourceSignature: "BIKi",
    sourceFormat: "bink",
    sourceVideoCodec: "binkvideo",
    sourceAudioCodecs: [],
    frames: 71,
    width: 96,
    height: 120,
    fpsNum: 30,
    fpsDen: 1,
    sourceDurationSeconds: 71 / 30,
    outputFile: "VS_small.webm",
    outputVideoCodec: "vp9",
    outputAudioCodecs: [],
  },
};

function usage() {
  return [
    "usage: node tools/verify_bink_browser_video_outputs.mjs [output-dir]",
    "                  [--manifest <path>] [--allow-missing]",
    "                  [--expect-current-zh]",
    "",
    "Verifies browser-decodable Bink sidecar outputs generated by",
    "transcode:bink-video. With --allow-missing, reports absent manifest/output",
    "files in JSON and exits 0; without it, missing or mismatched outputs fail.",
    "",
    "  output-dir              Directory holding generated WebM sidecars and",
    "                          bink-browser-video-manifest.json (default:",
    "                          artifacts/browser-video/bink).",
    "  --manifest <path>       Manifest path (default: <output-dir>/" +
      DEFAULT_MANIFEST_NAME + ").",
    "  --allow-missing         Do not fail when outputs are absent.",
    "  --expect-current-zh     Cross-check against current shipped payload facts.",
  ].join("\n");
}

function parseArgs(argv) {
  let outputDir = null;
  let manifestPath = null;
  let allowMissing = false;
  let expectCurrentZh = false;

  for (let i = 0; i < argv.length; ++i) {
    const arg = argv[i];
    if (arg === "--allow-missing") {
      allowMissing = true;
    } else if (arg === "--expect-current-zh") {
      expectCurrentZh = true;
    } else if (arg === "--manifest") {
      manifestPath = argv[++i];
      if (!manifestPath) {
        throw new Error("--manifest requires a path argument");
      }
    } else if (arg === "--help" || arg === "-h") {
      console.log(usage());
      process.exit(0);
    } else if (outputDir === null) {
      outputDir = arg;
    } else {
      throw new Error(`Unexpected argument: ${arg}`);
    }
  }

  const resolvedOutputDir = outputDir === null
    ? DEFAULT_OUTPUT_DIR
    : resolve(process.cwd(), outputDir);
  const resolvedManifestPath = manifestPath === null
    ? resolve(resolvedOutputDir, DEFAULT_MANIFEST_NAME)
    : resolve(process.cwd(), manifestPath);

  return {
    outputDir: resolvedOutputDir,
    manifestPath: resolvedManifestPath,
    allowMissing,
    expectCurrentZh,
  };
}

async function isFile(path) {
  try {
    const s = await stat(path);
    return s.isFile();
  } catch {
    return false;
  }
}

function probeFfprobe() {
  return new Promise((resolveProbe) => {
    const child = spawn("ffprobe", ["-version"], {
      stdio: ["ignore", "ignore", "ignore"],
    });
    child.on("error", () => resolveProbe(false));
    child.on("exit", (code) => resolveProbe(code === 0));
  });
}

function runFfprobe(mediaPath) {
  return new Promise((resolveProbe, reject) => {
    const child = spawn("ffprobe", [
      "-v", "error",
      "-count_frames",
      "-show_format",
      "-show_streams",
      "-of", "json",
      mediaPath,
    ], {
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => { stdout += chunk.toString(); });
    child.stderr.on("data", (chunk) => { stderr += chunk.toString(); });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code !== 0) {
        reject(new Error(`ffprobe exited ${code}: ${stderr.trim()}`));
        return;
      }
      try {
        resolveProbe(JSON.parse(stdout));
      } catch (error) {
        reject(new Error(`ffprobe produced non-JSON output: ${error.message}`));
      }
    });
  });
}

function isFiniteNumber(value) {
  return typeof value === "number" && Number.isFinite(value);
}

function isPositiveInteger(value) {
  return Number.isInteger(value) && value > 0;
}

function isNonEmptyString(value) {
  return typeof value === "string" && value.length > 0;
}

function nearlyEqual(left, right, epsilon = 0.05) {
  return Math.abs(Number(left) - Number(right)) <= epsilon;
}

function arrayEqual(left, right) {
  return Array.isArray(left)
    && Array.isArray(right)
    && left.length === right.length
    && left.every((value, index) => value === right[index]);
}

function resolveMaybeAbsolute(baseDir, candidate) {
  return isAbsolute(candidate) ? candidate : resolve(baseDir, candidate);
}

function videoStream(probe) {
  return probe.streams?.find((stream) => stream.codec_type === "video") ?? null;
}

function audioStreams(probe) {
  return probe.streams?.filter((stream) => stream.codec_type === "audio") ?? [];
}

function validateManifestEntry(entry) {
  const errors = [];
  const label = isNonEmptyString(entry?.sourceFile) ? entry.sourceFile : "<unnamed entry>";

  const requireString = (key) => {
    if (!isNonEmptyString(entry?.[key])) {
      errors.push(`${label}: missing or non-string ${key}`);
    }
  };
  const requirePositiveInt = (key) => {
    if (!isPositiveInteger(entry?.[key])) {
      errors.push(`${label}: ${key} must be a positive integer, got ${JSON.stringify(entry?.[key])}`);
    }
  };
  const requirePositiveNumber = (key) => {
    if (!isFiniteNumber(entry?.[key]) || entry[key] <= 0) {
      errors.push(`${label}: ${key} must be a positive number, got ${JSON.stringify(entry?.[key])}`);
    }
  };

  requireString("name");
  requireString("sourceFile");
  requireString("sourcePath");
  requirePositiveInt("sourceSize");
  requireString("sourceSignature");
  requireString("sourceFormat");
  requireString("sourceVideoCodec");
  if (!Array.isArray(entry?.sourceAudioCodecs)) {
    errors.push(`${label}: sourceAudioCodecs must be an array`);
  }
  requirePositiveInt("frames");
  requirePositiveInt("width");
  requirePositiveInt("height");
  requirePositiveInt("fpsNum");
  requirePositiveInt("fpsDen");
  requirePositiveNumber("sourceDurationSeconds");
  requireString("outputFile");
  requireString("outputPath");
  requirePositiveInt("outputSize");
  if (!String(entry?.outputFormat ?? "").includes("webm")) {
    errors.push(`${label}: outputFormat must include webm, got ${JSON.stringify(entry?.outputFormat)}`);
  }
  requireString("outputVideoCodec");
  if (!Array.isArray(entry?.outputAudioCodecs)) {
    errors.push(`${label}: outputAudioCodecs must be an array`);
  }
  requirePositiveInt("outputFrameCount");
  requirePositiveNumber("outputDurationSeconds");
  if (entry?.browserDecode?.container !== "webm") {
    errors.push(`${label}: browserDecode.container must be webm`);
  }
  if (entry?.browserDecode?.videoCodec !== "vp9") {
    errors.push(`${label}: browserDecode.videoCodec must be vp9`);
  }
  return errors;
}

function assertPinnedFacts(entry, errors) {
  const pinned = PINNED_FACTS[entry.sourceFile];
  if (!pinned) {
    errors.push(`${entry.sourceFile}: no pinned current-ZH facts registered`);
    return;
  }

  const checks = [
    ["name", entry.name, pinned.name],
    ["sourceSize", entry.sourceSize, pinned.sourceSize],
    ["sourceSignature", entry.sourceSignature, pinned.sourceSignature],
    ["sourceFormat", entry.sourceFormat, pinned.sourceFormat],
    ["sourceVideoCodec", entry.sourceVideoCodec, pinned.sourceVideoCodec],
    ["frames", entry.frames, pinned.frames],
    ["width", entry.width, pinned.width],
    ["height", entry.height, pinned.height],
    ["fpsNum", entry.fpsNum, pinned.fpsNum],
    ["fpsDen", entry.fpsDen, pinned.fpsDen],
    ["outputFile", entry.outputFile, pinned.outputFile],
    ["outputVideoCodec", entry.outputVideoCodec, pinned.outputVideoCodec],
  ];
  for (const [name, actual, expected] of checks) {
    if (actual !== expected) {
      errors.push(`${entry.sourceFile}: ${name} ${JSON.stringify(actual)} !== ${JSON.stringify(expected)}`);
    }
  }
  if (!arrayEqual(entry.sourceAudioCodecs, pinned.sourceAudioCodecs)) {
    errors.push(
      `${entry.sourceFile}: sourceAudioCodecs ${JSON.stringify(entry.sourceAudioCodecs)} !== ` +
      JSON.stringify(pinned.sourceAudioCodecs),
    );
  }
  if (!arrayEqual(entry.outputAudioCodecs, pinned.outputAudioCodecs)) {
    errors.push(
      `${entry.sourceFile}: outputAudioCodecs ${JSON.stringify(entry.outputAudioCodecs)} !== ` +
      JSON.stringify(pinned.outputAudioCodecs),
    );
  }
  if (!nearlyEqual(entry.sourceDurationSeconds, pinned.sourceDurationSeconds)) {
    errors.push(
      `${entry.sourceFile}: sourceDurationSeconds ${entry.sourceDurationSeconds} !== ` +
      `${pinned.sourceDurationSeconds}`,
    );
  }
}

async function assertManifestMatchesSourceBik(entry, errors) {
  const sourcePath = resolve(SOURCE_ASSETS_DIR, entry.sourceFile);
  if (!(await isFile(sourcePath))) {
    return;
  }

  const sourceStat = await stat(sourcePath);
  if (sourceStat.size !== entry.sourceSize) {
    errors.push(
      `${entry.sourceFile}: manifest sourceSize ${entry.sourceSize} !== actual source file size ${sourceStat.size}`,
    );
  }

  const file = await open(sourcePath, "r");
  try {
    const buf = Buffer.alloc(4);
    const { bytesRead } = await file.read(buf, 0, 4, 0);
    if (bytesRead === 4) {
      const signature = buf.toString("ascii", 0, 4);
      if (signature !== entry.sourceSignature) {
        errors.push(
          `${entry.sourceFile}: manifest sourceSignature ${JSON.stringify(entry.sourceSignature)} !== ` +
          `actual source signature ${JSON.stringify(signature)}`,
        );
      }
    }
  } finally {
    await file.close();
  }
}

async function loadManifest(path) {
  if (!(await isFile(path))) {
    return { manifest: null, errors: [] };
  }

  const errors = [];
  let parsed;
  try {
    parsed = JSON.parse(await readFile(path, "utf8"));
  } catch (error) {
    return { manifest: null, errors: [`manifest ${path} is not valid JSON: ${error.message}`] };
  }

  if (typeof parsed !== "object" || parsed === null) {
    errors.push("manifest root must be an object");
  }
  if (parsed?.schema !== MANIFEST_SCHEMA) {
    errors.push(`manifest schema ${JSON.stringify(parsed?.schema)} !== ${JSON.stringify(MANIFEST_SCHEMA)}`);
  }
  if (!Array.isArray(parsed?.payloads)) {
    errors.push("manifest.payloads must be an array");
  }
  return { manifest: errors.length === 0 ? parsed : null, errors };
}

function findEntry(manifest, sourceFile) {
  if (!manifest) {
    return null;
  }
  const matches = manifest.payloads.filter((entry) => entry?.sourceFile === sourceFile);
  if (matches.length === 0) {
    return null;
  }
  if (matches.length > 1) {
    return { duplicate: true };
  }
  return matches[0];
}

async function verifyOutputMedia(entry, outputPath, ffprobeAvailable, errors) {
  if (!ffprobeAvailable) {
    return { ffprobeVerified: false };
  }

  let probe;
  try {
    probe = await runFfprobe(outputPath);
  } catch (error) {
    errors.push(`${entry.sourceFile}: ffprobe failed on ${basename(outputPath)}: ${error.message}`);
    return { ffprobeVerified: false };
  }

  const stream = videoStream(probe);
  const outputAudio = audioStreams(probe);
  const result = {
    ffprobeVerified: true,
    video: stream ? {
      codecName: stream.codec_name ?? null,
      width: stream.width ?? null,
      height: stream.height ?? null,
      frameCount: Number(stream.nb_read_frames),
    } : null,
    audioCodecs: outputAudio.map((audio) => audio.codec_name),
    durationSeconds: Number(probe.format?.duration),
  };

  if (!stream) {
    errors.push(`${entry.sourceFile}: ffprobe found no video stream in ${basename(outputPath)}`);
    return result;
  }
  if (stream.codec_name !== entry.outputVideoCodec) {
    errors.push(
      `${entry.sourceFile}: ffprobe video codec ${JSON.stringify(stream.codec_name)} !== ` +
      `manifest ${JSON.stringify(entry.outputVideoCodec)}`,
    );
  }
  if (stream.width !== entry.width || stream.height !== entry.height) {
    errors.push(
      `${entry.sourceFile}: ffprobe dimensions ${stream.width}x${stream.height} !== ` +
      `${entry.width}x${entry.height}`,
    );
  }
  if (Number(stream.nb_read_frames) !== entry.outputFrameCount ||
      Number(stream.nb_read_frames) !== entry.frames) {
    errors.push(
      `${entry.sourceFile}: ffprobe frame count ${stream.nb_read_frames} !== ` +
      `manifest ${entry.outputFrameCount} / source ${entry.frames}`,
    );
  }
  if (!arrayEqual(result.audioCodecs, entry.outputAudioCodecs)) {
    errors.push(
      `${entry.sourceFile}: ffprobe audio codecs ${JSON.stringify(result.audioCodecs)} !== ` +
      JSON.stringify(entry.outputAudioCodecs),
    );
  }
  const duration = result.durationSeconds;
  if (Number.isFinite(duration)) {
    const tolerance = Math.max(0.05, Math.abs(entry.outputDurationSeconds) * 0.02);
    if (Math.abs(duration - entry.outputDurationSeconds) > tolerance) {
      errors.push(
        `${entry.sourceFile}: ffprobe duration ${duration.toFixed(6)}s outside tolerance of ` +
        `${entry.outputDurationSeconds}s`,
      );
    }
  }
  return result;
}

async function buildPayloadReport(sourceFile, options, manifest, ffprobeAvailable, errors) {
  const pinned = PINNED_FACTS[sourceFile];
  const entry = findEntry(manifest, sourceFile);

  const report = {
    sourceFile,
    expected: { ...pinned },
    present: false,
    duplicateEntry: false,
    entryErrors: [],
    output: null,
    note: null,
  };

  if (entry?.duplicate) {
    report.duplicateEntry = true;
    errors.push(`${sourceFile}: manifest contains more than one entry`);
    return report;
  }
  if (!entry) {
    report.note = "no manifest entry";
    return report;
  }

  report.entryErrors = validateManifestEntry(entry);
  errors.push(...report.entryErrors);
  if (report.entryErrors.length > 0) {
    return report;
  }

  if (options.expectCurrentZh) {
    assertPinnedFacts(entry, errors);
  }
  await assertManifestMatchesSourceBik(entry, errors);

  const outputPath = resolveMaybeAbsolute(options.outputDir, entry.outputPath);
  if (!(await isFile(outputPath))) {
    report.note = `manifest entry present but output file ${JSON.stringify(entry.outputFile)} absent`;
    return report;
  }

  const outputStat = await stat(outputPath);
  report.present = true;
  report.output = {
    path: outputPath,
    name: basename(outputPath),
    size: outputStat.size,
    format: entry.outputFormat,
    videoCodec: entry.outputVideoCodec,
    audioCodecs: entry.outputAudioCodecs,
    frameCount: entry.outputFrameCount,
    durationSeconds: entry.outputDurationSeconds,
  };
  report.output.ffprobe = await verifyOutputMedia(entry, outputPath, ffprobeAvailable, errors);

  return report;
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const errors = [];
  const ffprobeAvailable = await probeFfprobe();
  const loaded = await loadManifest(options.manifestPath);
  errors.push(...loaded.errors);
  const manifest = loaded.manifest;

  const payloads = [];
  for (const payloadFile of PAYLOAD_FILES) {
    payloads.push(await buildPayloadReport(
      payloadFile,
      options,
      manifest,
      ffprobeAvailable,
      errors,
    ));
  }

  const missingPayloads = payloads
    .filter((payload) => !payload.present)
    .map((payload) => payload.sourceFile);
  const ok = options.allowMissing
    ? errors.length === 0
    : errors.length === 0 && missingPayloads.length === 0;

  const report = {
    ok,
    source: SOURCE_TAG,
    outputDir: options.outputDir,
    manifestPath: options.manifestPath,
    manifestPresent: manifest !== null,
    ffprobe: {
      available: ffprobeAvailable,
      used: ffprobeAvailable && payloads.some((payload) => payload.present),
    },
    mode: options.allowMissing ? "allow-missing" : "strict",
    payloads,
    missingPayloads,
    errors,
    note:
      "Verifies browser-decodable WebM sidecars generated from the shipped " +
      "loose BIK payloads. Does not decode Bink in the provider or claim " +
      "original BinkVideoPlayer runtime playback.",
  };

  console.log(JSON.stringify(report, null, 2));
  if (!ok) {
    process.exitCode = 1;
  }
}

main().catch((error) => {
  console.error(error?.stack ?? error?.message ?? String(error));
  process.exitCode = 1;
});
