#pragma once

#include <cstddef>
#include <string>

struct ArchiveProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded = false;
	bool has_armor_ini = false;
	bool has_command_button_ini = false;
	bool has_game_data_ini = false;
	bool has_weapon_ini = false;
	bool has_map_cache_ini = false;
	bool has_water_ini = false;
	bool has_weather_ini = false;
	bool has_video_ini = false;
	bool has_default_video_ini = false;
	bool game_data_attempted = false;
	bool game_data_ok = false;
	bool game_data_loaded_archives = false;
	bool game_data_file_exists = false;
	bool game_data_original_ini_load = false;
	bool water_attempted = false;
	bool water_ok = false;
	bool water_loaded_archives = false;
	bool water_file_exists = false;
	bool water_original_ini_load = false;
	bool water_transparency_loaded = false;
	bool weather_attempted = false;
	bool weather_ok = false;
	bool weather_loaded_archives = false;
	bool weather_file_exists = false;
	bool weather_original_ini_load = false;
	bool video_attempted = false;
	bool video_ok = false;
	bool video_loaded_archives = false;
	bool video_file_exists = false;
	bool video_default_file_exists = false;
	bool video_original_ini_load = false;
	bool video_default_original_ini_load = false;
	bool video_shipped_original_ini_load = false;
	bool map_cache_attempted = false;
	bool map_cache_ok = false;
	bool map_cache_loaded_archives = false;
	bool map_cache_file_exists = false;
	bool map_cache_game_text_loaded = false;
	bool map_cache_name_key_generator_loaded = false;
	bool map_cache_original_ini_load = false;
	bool has_generals_csf = false;
	bool game_text_attempted = false;
	bool game_text_ok = false;
	bool game_text_title_label = false;
	bool game_text_control_bar_label = false;
	std::size_t indexed_file_count = 0;
	std::size_t sample_bytes = 0;
	std::size_t game_data_bytes = 0;
	std::size_t game_data_parsed_fields = 0;
	std::size_t water_bytes = 0;
	std::size_t water_parsed_fields = 0;
	std::size_t water_set_count = 0;
	std::size_t weather_bytes = 0;
	std::size_t weather_parsed_fields = 0;
	std::size_t video_bytes = 0;
	std::size_t video_default_bytes = 0;
	std::size_t video_parsed_fields = 0;
	std::size_t video_count = 0;
	std::size_t map_cache_bytes = 0;
	std::size_t map_cache_maps = 0;
	std::size_t map_cache_multiplayer_maps = 0;
	std::size_t map_cache_official_maps = 0;
	std::size_t game_text_control_bar_label_count = 0;
	std::string game_data_shell_map_name;
	bool game_data_use_fps_limit = false;
	bool game_data_use_cloud_map = false;
	int game_data_frames_per_second_limit = 0;
	int game_data_max_shell_screens = 0;
	int game_data_max_particle_count = 0;
	float game_data_default_structure_rubble_height = 0.0f;
	float game_data_group_select_volume_base = 0.0f;
	std::string game_data_source;
	std::string water_source;
	std::string water_morning_sky_texture;
	std::string water_morning_water_texture;
	std::string water_night_sky_texture;
	std::string water_night_water_texture;
	std::string water_standing_water_texture;
	int water_morning_repeat_count = 0;
	int water_night_repeat_count = 0;
	float water_morning_sky_texels_per_unit = 0.0f;
	float water_night_sky_texels_per_unit = 0.0f;
	float water_morning_u_scroll_per_ms = 0.0f;
	float water_morning_v_scroll_per_ms = 0.0f;
	float water_night_u_scroll_per_ms = 0.0f;
	float water_night_v_scroll_per_ms = 0.0f;
	float water_transparent_depth = 0.0f;
	float water_transparent_min_opacity = 0.0f;
	bool water_additive_blending = false;
	std::string weather_source;
	std::string weather_snow_texture;
	bool weather_snow_enabled = false;
	bool weather_use_point_sprites = false;
	float weather_snow_box_dimensions = 0.0f;
	float weather_snow_box_density = 0.0f;
	float weather_snow_frequency_scale_x = 0.0f;
	float weather_snow_frequency_scale_y = 0.0f;
	float weather_snow_amplitude = 0.0f;
	float weather_snow_velocity = 0.0f;
	float weather_snow_point_size = 0.0f;
	float weather_snow_quad_size = 0.0f;
	float weather_snow_max_point_size = 0.0f;
	float weather_snow_min_point_size = 0.0f;
	std::string video_source;
	std::string video_first_internal_name;
	std::string video_first_filename;
	std::string video_sample_internal_name;
	std::string video_sample_filename;
	std::string map_cache_source;
	bool map_cache_has_shell_map_md = false;
	bool map_cache_has_tournament_desert = false;
	bool map_cache_shell_map_md_display_name = false;
	bool map_cache_tournament_desert_display_name = false;
	int map_cache_shell_map_md_players = 0;
	int map_cache_tournament_desert_players = 0;
	std::string archive_path;
};

ArchiveProbeResult probe_original_archive(const char *archive_path);
