#pragma once

#include <cstddef>
#include <string>

struct ArchiveProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded = false;
	bool has_armor_ini = false;
	bool has_damage_fx_ini = false;
	bool has_command_button_ini = false;
	bool has_command_set_ini = false;
	bool has_control_bar_scheme_ini = false;
	bool has_default_control_bar_scheme_ini = false;
	bool has_crate_ini = false;
	bool has_player_template_ini = false;
	bool has_game_data_ini = false;
	bool has_science_ini = false;
	bool has_special_power_ini = false;
	bool has_multiplayer_ini = false;
	bool has_terrain_ini = false;
	bool has_roads_ini = false;
	bool has_draw_group_info_ini = false;
	bool has_upgrade_ini = false;
	bool has_weapon_ini = false;
	bool has_particle_system_ini = false;
	bool has_map_cache_ini = false;
	bool has_water_ini = false;
	bool has_weather_ini = false;
	bool has_video_ini = false;
	bool has_default_video_ini = false;
	bool armor_attempted = false;
	bool armor_ok = false;
	bool armor_loaded_archives = false;
	bool armor_file_exists = false;
	bool armor_name_key_generator_loaded = false;
	bool armor_original_ini_load = false;
	bool damage_fx_attempted = false;
	bool damage_fx_ok = false;
	bool damage_fx_loaded_archives = false;
	bool damage_fx_file_exists = false;
	bool damage_fx_name_key_generator_loaded = false;
	bool damage_fx_fx_list_store_loaded = false;
	bool damage_fx_store_loaded = false;
	bool damage_fx_original_ini_load = false;
	bool science_attempted = false;
	bool science_ok = false;
	bool science_loaded_archives = false;
	bool science_file_exists = false;
	bool science_game_text_loaded = false;
	bool science_name_key_generator_loaded = false;
	bool science_original_ini_load = false;
	bool special_power_attempted = false;
	bool special_power_ok = false;
	bool special_power_loaded_archives = false;
	bool special_power_file_exists = false;
	bool special_power_science_file_exists = false;
	bool special_power_game_text_loaded = false;
	bool special_power_name_key_generator_loaded = false;
	bool special_power_audio_manager_loaded = false;
	bool special_power_science_original_ini_load = false;
	bool special_power_original_ini_load = false;
	bool command_button_attempted = false;
	bool command_button_ok = false;
	bool command_button_loaded_archives = false;
	bool command_button_file_exists = false;
	bool command_button_science_file_exists = false;
	bool command_button_special_power_file_exists = false;
	bool command_button_upgrade_file_exists = false;
	bool command_button_name_key_generator_loaded = false;
	bool command_button_science_original_ini_load = false;
	bool command_button_special_power_original_ini_load = false;
	bool command_button_upgrade_original_ini_load = false;
	bool command_button_original_ini_load = false;
	bool command_button_filtered_from_shipped = false;
	bool command_button_special_power_option_pairing_valid = false;
	bool command_set_attempted = false;
	bool command_set_ok = false;
	bool command_set_loaded_archives = false;
	bool command_set_file_exists = false;
	bool command_set_command_button_file_exists = false;
	bool command_set_special_power_file_exists = false;
	bool command_set_upgrade_file_exists = false;
	bool command_set_name_key_generator_loaded = false;
	bool command_set_special_power_original_ini_load = false;
	bool command_set_upgrade_original_ini_load = false;
	bool command_set_command_button_original_ini_load = false;
	bool command_set_original_ini_load = false;
	bool command_set_filtered_from_shipped = false;
	bool control_bar_scheme_attempted = false;
	bool control_bar_scheme_ok = false;
	bool control_bar_scheme_loaded_archives = false;
	bool control_bar_scheme_default_file_exists = false;
	bool control_bar_scheme_file_exists = false;
	bool control_bar_scheme_name_key_generator_loaded = false;
	bool control_bar_scheme_mapped_images_loaded = false;
	bool control_bar_scheme_control_bar_loaded = false;
	bool control_bar_scheme_original_default_ini_load = false;
	bool control_bar_scheme_original_ini_load = false;
	bool crate_attempted = false;
	bool crate_ok = false;
	bool crate_loaded_archives = false;
	bool crate_file_exists = false;
	bool crate_science_file_exists = false;
	bool crate_game_text_loaded = false;
	bool crate_name_key_generator_loaded = false;
	bool crate_science_original_ini_load = false;
	bool crate_original_ini_load = false;
	bool crate_filtered_from_shipped = false;
	bool player_template_attempted = false;
	bool player_template_ok = false;
	bool player_template_loaded_archives = false;
	bool player_template_file_exists = false;
	bool player_template_science_file_exists = false;
	bool player_template_game_text_loaded = false;
	bool player_template_name_key_generator_loaded = false;
	bool player_template_science_original_ini_load = false;
	bool player_template_original_ini_load = false;
	bool game_data_attempted = false;
	bool game_data_ok = false;
	bool game_data_loaded_archives = false;
	bool game_data_file_exists = false;
	bool game_data_original_ini_load = false;
	bool multiplayer_attempted = false;
	bool multiplayer_ok = false;
	bool multiplayer_loaded_archives = false;
	bool multiplayer_file_exists = false;
	bool multiplayer_original_ini_load = false;
	bool terrain_attempted = false;
	bool terrain_ok = false;
	bool terrain_loaded_archives = false;
	bool terrain_file_exists = false;
	bool terrain_original_ini_load = false;
	bool terrain_roads_attempted = false;
	bool terrain_roads_ok = false;
	bool terrain_roads_loaded_archives = false;
	bool terrain_roads_file_exists = false;
	bool terrain_roads_original_ini_load = false;
	bool draw_group_info_attempted = false;
	bool draw_group_info_ok = false;
	bool draw_group_info_loaded_archives = false;
	bool draw_group_info_file_exists = false;
	bool draw_group_info_original_ini_load = false;
	bool mapped_image_attempted = false;
	bool mapped_image_ok = false;
	bool mapped_image_loaded_archives = false;
	bool mapped_image_file_exists = false;
	bool mapped_image_name_key_generator_loaded = false;
	bool mapped_image_original_ini_load = false;
	bool upgrade_attempted = false;
	bool upgrade_ok = false;
	bool upgrade_loaded_archives = false;
	bool upgrade_file_exists = false;
	bool upgrade_name_key_generator_loaded = false;
	bool upgrade_original_ini_load = false;
	bool weapon_attempted = false;
	bool weapon_ok = false;
	bool weapon_loaded_archives = false;
	bool weapon_file_exists = false;
	bool weapon_particle_file_exists = false;
	bool weapon_name_key_generator_loaded = false;
	bool weapon_fx_list_store_loaded = false;
	bool weapon_particle_system_manager_loaded = false;
	bool weapon_store_loaded = false;
	bool weapon_particle_original_ini_load = false;
	bool weapon_original_ini_load = false;
	bool water_attempted = false;
	bool water_ok = false;
	bool water_loaded_archives = false;
	bool water_file_exists = false;
	bool water_original_ini_load = false;
	bool water_transparency_loaded = false;
	bool weather_attempted = false;
	bool weather_ok = false;
	bool weather_loaded_archives = false;
	bool weather_file_exists = false;
	bool weather_original_ini_load = false;
	bool video_attempted = false;
	bool video_ok = false;
	bool video_loaded_archives = false;
	bool video_file_exists = false;
	bool video_default_file_exists = false;
	bool video_original_ini_load = false;
	bool video_default_original_ini_load = false;
	bool video_shipped_original_ini_load = false;
	bool map_cache_attempted = false;
	bool map_cache_ok = false;
	bool map_cache_loaded_archives = false;
	bool map_cache_file_exists = false;
	bool map_cache_game_text_loaded = false;
	bool map_cache_name_key_generator_loaded = false;
	bool map_cache_original_ini_load = false;
	bool has_generals_csf = false;
	bool game_text_attempted = false;
	bool game_text_ok = false;
	bool game_text_title_label = false;
	bool game_text_control_bar_label = false;
	std::size_t indexed_file_count = 0;
	std::size_t sample_bytes = 0;
	std::size_t armor_bytes = 0;
	std::size_t armor_parsed_fields = 0;
	std::size_t damage_fx_bytes = 0;
	std::size_t damage_fx_parsed_fields = 0;
	std::size_t science_bytes = 0;
	std::size_t science_parsed_fields = 0;
	std::size_t science_count = 0;
	std::size_t special_power_bytes = 0;
	std::size_t special_power_science_bytes = 0;
	std::size_t special_power_parsed_fields = 0;
	std::size_t special_power_count = 0;
	std::size_t command_button_bytes = 0;
	std::size_t command_button_science_bytes = 0;
	std::size_t command_button_special_power_bytes = 0;
	std::size_t command_button_upgrade_bytes = 0;
	std::size_t command_button_filtered_bytes = 0;
	std::size_t command_button_filtered_blocks = 0;
	std::size_t command_button_parsed_fields = 0;
	std::size_t command_button_count = 0;
	std::size_t command_set_bytes = 0;
	std::size_t command_set_command_button_bytes = 0;
	std::size_t command_set_special_power_bytes = 0;
	std::size_t command_set_upgrade_bytes = 0;
	std::size_t command_set_filtered_command_button_bytes = 0;
	std::size_t command_set_filtered_command_button_blocks = 0;
	std::size_t command_set_filtered_command_set_bytes = 0;
	std::size_t command_set_filtered_command_set_blocks = 0;
	std::size_t command_set_parsed_fields = 0;
	std::size_t command_set_command_button_count = 0;
	std::size_t command_set_count = 0;
	std::size_t control_bar_scheme_default_bytes = 0;
	std::size_t control_bar_scheme_bytes = 0;
	std::size_t control_bar_scheme_mapped_image_count = 0;
	std::size_t control_bar_scheme_parsed_fields = 0;
	std::size_t crate_bytes = 0;
	std::size_t crate_science_bytes = 0;
	std::size_t crate_filtered_bytes = 0;
	std::size_t crate_filtered_blocks = 0;
	std::size_t crate_parsed_fields = 0;
	std::size_t crate_template_count = 0;
	std::size_t player_template_bytes = 0;
	std::size_t player_template_science_bytes = 0;
	std::size_t player_template_parsed_fields = 0;
	std::size_t player_template_count = 0;
	std::size_t player_template_side_count = 0;
	std::size_t game_data_bytes = 0;
	std::size_t game_data_parsed_fields = 0;
	std::size_t multiplayer_bytes = 0;
	std::size_t multiplayer_parsed_fields = 0;
	std::size_t multiplayer_color_count = 0;
	std::size_t multiplayer_starting_money_count = 0;
	std::size_t terrain_bytes = 0;
	std::size_t terrain_parsed_fields = 0;
	std::size_t terrain_count = 0;
	std::size_t terrain_roads_bytes = 0;
	std::size_t terrain_roads_parsed_fields = 0;
	std::size_t terrain_roads_road_count = 0;
	std::size_t terrain_roads_bridge_count = 0;
	std::size_t draw_group_info_bytes = 0;
	std::size_t draw_group_info_parsed_fields = 0;
	std::size_t mapped_image_bytes = 0;
	std::size_t mapped_image_parsed_fields = 0;
	std::size_t mapped_image_file_count = 0;
	std::size_t mapped_image_count = 0;
	std::size_t upgrade_bytes = 0;
	std::size_t upgrade_parsed_fields = 0;
	std::size_t upgrade_count = 0;
	std::size_t weapon_bytes = 0;
	std::size_t weapon_particle_bytes = 0;
	std::size_t weapon_particle_template_count = 0;
	std::size_t weapon_parsed_fields = 0;
	std::size_t water_bytes = 0;
	std::size_t water_parsed_fields = 0;
	std::size_t water_set_count = 0;
	std::size_t weather_bytes = 0;
	std::size_t weather_parsed_fields = 0;
	std::size_t video_bytes = 0;
	std::size_t video_default_bytes = 0;
	std::size_t video_parsed_fields = 0;
	std::size_t video_count = 0;
	std::size_t map_cache_bytes = 0;
	std::size_t map_cache_maps = 0;
	std::size_t map_cache_multiplayer_maps = 0;
	std::size_t map_cache_official_maps = 0;
	std::size_t game_text_control_bar_label_count = 0;
	std::string game_data_shell_map_name;
	std::string armor_source;
	std::string damage_fx_source;
	std::string science_source;
	std::string special_power_source;
	std::string command_button_source;
	std::string command_set_source;
	std::string control_bar_scheme_source;
	std::string crate_source;
	std::string draw_group_info_source;
	std::string mapped_image_source;
	std::string player_template_source;
	bool armor_no_armor_found = false;
	bool armor_human_armor_found = false;
	bool armor_tank_armor_found = false;
	float armor_no_armor_explosion_damage = 0.0f;
	float armor_no_armor_hazard_cleanup_damage = 0.0f;
	float armor_human_crush_damage = 0.0f;
	float armor_human_armor_piercing_damage = 0.0f;
	float armor_human_flame_damage = 0.0f;
	float armor_tank_small_arms_damage = 0.0f;
	float armor_tank_radiation_damage = 0.0f;
	float armor_tank_microwave_damage = 0.0f;
	bool damage_fx_default_found = false;
	bool damage_fx_tank_found = false;
	bool damage_fx_small_tank_found = false;
	bool damage_fx_structure_found = false;
	bool damage_fx_infantry_found = false;
	unsigned int damage_fx_default_explosion_throttle = 0;
	unsigned int damage_fx_tank_small_arms_throttle = 0;
	unsigned int damage_fx_small_tank_comanche_throttle = 0;
	unsigned int damage_fx_structure_flame_throttle = 0;
	unsigned int damage_fx_infantry_sniper_throttle = 0;
	bool science_america_found = false;
	bool science_rank3_found = false;
	bool science_paladin_found = false;
	bool science_paladin_name_loaded = false;
	bool science_paladin_description_loaded = false;
	int science_america_purchase_cost = 0;
	int science_paladin_purchase_cost = 0;
	bool science_america_grantable = false;
	bool science_paladin_grantable = false;
	bool special_power_daisy_cutter_found = false;
	bool special_power_carpet_bomb_found = false;
	bool special_power_crate_drop_found = false;
	bool special_power_neutron_missile_found = false;
	bool special_power_scud_storm_found = false;
	int special_power_daisy_cutter_enum = 0;
	int special_power_carpet_bomb_enum = 0;
	int special_power_crate_drop_enum = 0;
	int special_power_daisy_cutter_reload_frames = 0;
	int special_power_carpet_bomb_reload_frames = 0;
	int special_power_crate_drop_reload_frames = 0;
	bool special_power_daisy_cutter_required_science_valid = false;
	bool special_power_crate_drop_required_science_valid = false;
	bool special_power_daisy_cutter_public_timer = false;
	bool special_power_carpet_bomb_public_timer = false;
	bool special_power_crate_drop_public_timer = false;
	bool special_power_daisy_cutter_shared_synced_timer = false;
	bool special_power_carpet_bomb_shared_synced_timer = false;
	bool special_power_crate_drop_shared_synced_timer = false;
	int special_power_daisy_cutter_view_object_duration_frames = 0;
	int special_power_carpet_bomb_view_object_duration_frames = 0;
	int special_power_crate_drop_view_object_duration_frames = 0;
	float special_power_daisy_cutter_view_object_range = 0.0f;
	float special_power_carpet_bomb_view_object_range = 0.0f;
	float special_power_crate_drop_view_object_range = 0.0f;
	float special_power_daisy_cutter_radius_cursor_radius = 0.0f;
	float special_power_carpet_bomb_radius_cursor_radius = 0.0f;
	float special_power_crate_drop_radius_cursor_radius = 0.0f;
	bool special_power_daisy_cutter_shortcut_power = false;
	bool special_power_carpet_bomb_shortcut_power = false;
	bool special_power_crate_drop_shortcut_power = false;
	int special_power_daisy_cutter_academy_classification = 0;
	int special_power_carpet_bomb_academy_classification = 0;
	std::string special_power_daisy_cutter_required_science;
	std::string special_power_crate_drop_required_science;
	std::string special_power_neutron_missile_initiate_at_location_sound;
	std::string special_power_scud_storm_initiate_sound;
	bool command_button_flash_bang_upgrade_found = false;
	int command_button_flash_bang_upgrade_command = 0;
	int command_button_flash_bang_upgrade_border = 0;
	std::string command_button_flash_bang_upgrade_name;
	std::string command_button_flash_bang_upgrade_label;
	std::string command_button_flash_bang_upgrade_description;
	bool command_button_ranger_capture_found = false;
	int command_button_ranger_capture_command = 0;
	unsigned int command_button_ranger_capture_options = 0;
	int command_button_ranger_capture_border = 0;
	std::string command_button_ranger_capture_upgrade_name;
	std::string command_button_ranger_capture_special_power_name;
	std::string command_button_ranger_capture_label;
	std::string command_button_ranger_capture_description;
	std::string command_button_ranger_capture_cursor;
	std::string command_button_ranger_capture_invalid_cursor;
	bool command_button_ranger_capture_has_enemy_target = false;
	bool command_button_ranger_capture_has_neutral_target = false;
	bool command_button_ranger_capture_has_multi_select = false;
	bool command_button_ranger_capture_has_need_upgrade = false;
	bool command_button_ranger_capture_has_need_special_power_science = false;
	bool command_button_flash_bang_switch_found = false;
	int command_button_flash_bang_switch_command = 0;
	unsigned int command_button_flash_bang_switch_options = 0;
	int command_button_flash_bang_switch_weapon_slot = 0;
	int command_button_flash_bang_switch_border = 0;
	std::string command_button_flash_bang_switch_upgrade_name;
	std::string command_button_flash_bang_switch_label;
	std::string command_button_flash_bang_switch_description;
	bool command_button_flash_bang_switch_has_check_like = false;
	bool command_button_flash_bang_switch_has_multi_select = false;
	bool command_button_flash_bang_switch_has_need_upgrade = false;
	bool command_set_ranger_found = false;
	std::string command_set_ranger_slot1;
	std::string command_set_ranger_slot2;
	std::string command_set_ranger_slot4;
	std::string command_set_ranger_slot11;
	std::string command_set_ranger_slot13;
	std::string command_set_ranger_slot14;
	int command_set_ranger_slot1_command = 0;
	int command_set_ranger_slot2_command = 0;
	int command_set_ranger_slot4_command = 0;
	int command_set_ranger_slot11_command = 0;
	int command_set_ranger_slot13_command = 0;
	int command_set_ranger_slot14_command = 0;
	int command_set_ranger_slot2_weapon_slot = 0;
	int command_set_ranger_slot4_weapon_slot = 0;
	std::string command_set_ranger_slot1_special_power;
	std::string command_set_ranger_slot1_upgrade;
	std::string command_set_ranger_slot4_upgrade;
	bool control_bar_scheme_default_found = false;
	std::string control_bar_scheme_default_queue_image;
	std::string control_bar_scheme_default_right_hud_image;
	std::string control_bar_scheme_default_base_image;
	int control_bar_scheme_default_base_layer = 0;
	int control_bar_scheme_default_base_width = 0;
	int control_bar_scheme_default_base_height = 0;
	bool control_bar_scheme_america_found = false;
	std::string control_bar_scheme_america_side;
	std::string control_bar_scheme_america_queue_image;
	std::string control_bar_scheme_america_right_hud_image;
	std::string control_bar_scheme_america_command_marker_image;
	std::string control_bar_scheme_america_power_purchase_image;
	std::string control_bar_scheme_america_base_image;
	int control_bar_scheme_america_screen_x = 0;
	int control_bar_scheme_america_screen_y = 0;
	int control_bar_scheme_america_base_layer = 0;
	int control_bar_scheme_america_base_x = 0;
	int control_bar_scheme_america_base_y = 0;
	int control_bar_scheme_america_base_width = 0;
	int control_bar_scheme_america_base_height = 0;
	bool control_bar_scheme_gla_found = false;
	std::string control_bar_scheme_gla_side;
	std::string control_bar_scheme_gla_right_hud_image;
	std::string control_bar_scheme_gla_command_marker_image;
	std::string control_bar_scheme_gla_power_purchase_image;
	std::string control_bar_scheme_gla_base_image;
	bool control_bar_scheme_china_found = false;
	std::string control_bar_scheme_china_side;
	std::string control_bar_scheme_china_right_hud_image;
	std::string control_bar_scheme_china_command_marker_image;
	std::string control_bar_scheme_china_power_purchase_image;
	std::string control_bar_scheme_china_gen_arrow_image;
	std::string control_bar_scheme_china_base_image;
	bool crate_salvage_found = false;
	float crate_salvage_creation_chance = 0.0f;
	bool crate_salvage_salvager_kindof = false;
	bool crate_salvage_killer_science_valid = false;
	std::size_t crate_salvage_object_count = 0;
	std::string crate_salvage_object_name;
	float crate_salvage_object_chance = 0.0f;
	bool crate_elite_found = false;
	float crate_elite_creation_chance = 0.0f;
	int crate_elite_veterancy_level = 0;
	std::size_t crate_elite_object_count = 0;
	std::string crate_elite_first_object;
	float crate_elite_first_chance = 0.0f;
	std::string crate_elite_second_object;
	float crate_elite_second_chance = 0.0f;
	bool crate_heroic_found = false;
	float crate_heroic_creation_chance = 0.0f;
	int crate_heroic_veterancy_level = 0;
	std::size_t crate_heroic_object_count = 0;
	std::string crate_heroic_first_object;
	float crate_heroic_first_chance = 0.0f;
	std::string crate_heroic_third_object;
	float crate_heroic_third_chance = 0.0f;
	bool crate_gla02_100_found = false;
	bool crate_gla02_100_owned_by_maker = false;
	std::string crate_gla02_100_object;
	float crate_gla02_100_object_chance = 0.0f;
	bool crate_gla02_2500_found = false;
	bool crate_gla02_2500_owned_by_maker = false;
	std::string crate_gla02_2500_object;
	float crate_gla02_2500_object_chance = 0.0f;
	std::string draw_group_info_font_name;
	int draw_group_info_font_size = 0;
	bool draw_group_info_font_is_bold = false;
	bool draw_group_info_use_player_color = false;
	unsigned int draw_group_info_color_for_text = 0;
	unsigned int draw_group_info_color_for_text_drop_shadow = 0;
	int draw_group_info_drop_shadow_offset_x = 0;
	int draw_group_info_drop_shadow_offset_y = 0;
	bool draw_group_info_using_pixel_offset_x = false;
	bool draw_group_info_using_pixel_offset_y = false;
	int draw_group_info_pixel_offset_x = 0;
	int draw_group_info_pixel_offset_y = 0;
	float draw_group_info_percent_offset_x = 0.0f;
	float draw_group_info_percent_offset_y = 0.0f;
	bool mapped_image_sa_chinook_found = false;
	std::string mapped_image_sa_chinook_texture;
	int mapped_image_sa_chinook_texture_width = 0;
	int mapped_image_sa_chinook_texture_height = 0;
	int mapped_image_sa_chinook_width = 0;
	int mapped_image_sa_chinook_height = 0;
	unsigned int mapped_image_sa_chinook_status = 0;
	float mapped_image_sa_chinook_uv_lo_x = 0.0f;
	float mapped_image_sa_chinook_uv_lo_y = 0.0f;
	float mapped_image_sa_chinook_uv_hi_x = 0.0f;
	float mapped_image_sa_chinook_uv_hi_y = 0.0f;
	bool mapped_image_watermark_china_found = false;
	std::string mapped_image_watermark_china_texture;
	int mapped_image_watermark_china_width = 0;
	int mapped_image_watermark_china_height = 0;
	unsigned int mapped_image_watermark_china_status = 0;
	bool mapped_image_watermark_china_rotated = false;
	bool player_template_america_found = false;
	bool player_template_china_found = false;
	bool player_template_gla_found = false;
	bool player_template_observer_found = false;
	bool player_template_air_force_found = false;
	bool player_template_boss_found = false;
	bool player_template_america_display_name_loaded = false;
	std::string player_template_america_side;
	std::string player_template_america_base_side;
	bool player_template_america_playable = false;
	bool player_template_america_old_faction = false;
	int player_template_america_start_money = 0;
	std::size_t player_template_america_intrinsic_science_count = 0;
	bool player_template_america_intrinsic_science_valid = false;
	std::string player_template_america_starting_building;
	std::string player_template_america_starting_unit0;
	std::string player_template_america_shortcut_command_set;
	std::string player_template_america_shortcut_win_name;
	int player_template_america_shortcut_button_count = 0;
	std::string player_template_america_load_screen;
	std::string player_template_america_score_screen;
	std::string player_template_america_load_music;
	std::string player_template_america_score_music;
	std::string player_template_america_beacon;
	bool player_template_observer_is_observer = false;
	bool player_template_observer_playable = false;
	std::string player_template_observer_side;
	std::string player_template_observer_load_screen;
	std::string player_template_observer_beacon;
	std::string player_template_air_force_side;
	std::string player_template_air_force_base_side;
	bool player_template_air_force_playable = false;
	bool player_template_air_force_old_faction = false;
	std::string player_template_air_force_starting_building;
	std::string player_template_air_force_starting_unit0;
	std::string player_template_air_force_shortcut_command_set;
	int player_template_air_force_shortcut_button_count = 0;
	std::string player_template_boss_side;
	std::string player_template_boss_base_side;
	bool player_template_boss_playable = false;
	bool player_template_boss_old_faction = false;
	std::size_t player_template_boss_intrinsic_science_count = 0;
	bool player_template_boss_intrinsic_sciences_valid = false;
	std::string player_template_boss_starting_building;
	std::string player_template_boss_starting_unit0;
	std::string player_template_boss_shortcut_command_set;
	std::string player_template_boss_shortcut_win_name;
	int player_template_boss_shortcut_button_count = 0;
	bool game_data_use_fps_limit = false;
	bool game_data_use_cloud_map = false;
	int game_data_frames_per_second_limit = 0;
	int game_data_max_shell_screens = 0;
	int game_data_max_particle_count = 0;
	float game_data_default_structure_rubble_height = 0.0f;
	float game_data_group_select_volume_base = 0.0f;
	std::string game_data_source;
	std::string multiplayer_source;
	int multiplayer_start_countdown_seconds = 0;
	int multiplayer_max_beacons_per_player = 0;
	bool multiplayer_use_shroud = false;
	bool multiplayer_show_random_player_template = false;
	bool multiplayer_show_random_start_pos = false;
	bool multiplayer_show_random_color = false;
	bool multiplayer_gold_color_found = false;
	bool multiplayer_purple_color_found = false;
	unsigned int multiplayer_gold_color = 0;
	unsigned int multiplayer_purple_night_color = 0;
	unsigned int multiplayer_chat_default_color = 0;
	unsigned int multiplayer_chat_game_color = 0;
	unsigned int multiplayer_chat_player_normal_color = 0;
	unsigned int multiplayer_chat_self_color = 0;
	unsigned int multiplayer_chat_map_selected_color = 0;
	int multiplayer_starting_money_first = 0;
	int multiplayer_starting_money_second = 0;
	int multiplayer_starting_money_third = 0;
	int multiplayer_starting_money_fourth = 0;
	int multiplayer_default_starting_money = 0;
	std::string terrain_source;
	bool terrain_transition_found = false;
	bool terrain_asphalt_found = false;
	bool terrain_desert_dry_found = false;
	bool terrain_beach_tropical_found = false;
	bool terrain_snow_flat_found = false;
	std::string terrain_transition_texture;
	std::string terrain_asphalt_texture;
	std::string terrain_desert_dry_texture;
	std::string terrain_beach_tropical_texture;
	std::string terrain_snow_flat_texture;
	int terrain_transition_class = 0;
	int terrain_asphalt_class = 0;
	int terrain_desert_dry_class = 0;
	int terrain_beach_tropical_class = 0;
	int terrain_snow_flat_class = 0;
	bool terrain_asphalt_blend_edges = false;
	bool terrain_asphalt_restrict_construction = false;
	std::string terrain_roads_source;
	std::string upgrade_source;
	std::string weapon_source;
	bool upgrade_veteran_found = false;
	bool upgrade_elite_found = false;
	bool upgrade_heroic_found = false;
	bool upgrade_flash_bang_found = false;
	bool upgrade_capture_building_found = false;
	bool upgrade_laser_missiles_found = false;
	bool upgrade_china_mines_found = false;
	bool upgrade_america_radar_found = false;
	std::string upgrade_flash_bang_display_name;
	std::string upgrade_capture_building_display_name;
	std::string upgrade_laser_missiles_display_name;
	std::string upgrade_china_mines_display_name;
	std::string upgrade_america_radar_display_name;
	std::string upgrade_flash_bang_research_sound;
	std::string upgrade_laser_missiles_research_sound;
	std::string upgrade_china_mines_research_sound;
	std::string upgrade_america_radar_research_sound;
	int upgrade_flash_bang_type = 0;
	int upgrade_capture_building_type = 0;
	int upgrade_laser_missiles_type = 0;
	int upgrade_china_mines_type = 0;
	int upgrade_america_radar_type = 0;
	int upgrade_flash_bang_build_frames = 0;
	int upgrade_capture_building_build_frames = 0;
	int upgrade_laser_missiles_build_frames = 0;
	int upgrade_china_mines_build_frames = 0;
	int upgrade_america_radar_build_frames = 0;
	int upgrade_flash_bang_cost = 0;
	int upgrade_capture_building_cost = 0;
	int upgrade_laser_missiles_cost = 0;
	int upgrade_china_mines_cost = 0;
	int upgrade_america_radar_cost = 0;
	int upgrade_america_radar_academy_classification = 0;
	bool weapon_tomahawk_exhaust_template_found = false;
	bool weapon_heroic_tomahawk_exhaust_template_found = false;
	bool weapon_ranger_found = false;
	bool weapon_crusader_found = false;
	bool weapon_tomahawk_found = false;
	float weapon_ranger_primary_damage = 0.0f;
	float weapon_ranger_attack_range = 0.0f;
	int weapon_ranger_delay_frames = 0;
	int weapon_ranger_clip_size = 0;
	int weapon_ranger_clip_reload_frames = 0;
	int weapon_ranger_damage_type = 0;
	int weapon_ranger_death_type = 0;
	std::string weapon_ranger_fire_sound;
	float weapon_crusader_primary_damage = 0.0f;
	float weapon_crusader_primary_damage_radius = 0.0f;
	float weapon_crusader_attack_range = 0.0f;
	int weapon_crusader_delay_frames = 0;
	int weapon_crusader_clip_size = 0;
	int weapon_crusader_damage_type = 0;
	int weapon_crusader_death_type = 0;
	std::string weapon_crusader_fire_sound;
	float weapon_tomahawk_primary_damage = 0.0f;
	float weapon_tomahawk_primary_damage_radius = 0.0f;
	float weapon_tomahawk_secondary_damage = 0.0f;
	float weapon_tomahawk_secondary_damage_radius = 0.0f;
	float weapon_tomahawk_attack_range = 0.0f;
	float weapon_tomahawk_minimum_attack_range = 0.0f;
	int weapon_tomahawk_pre_attack_delay_frames = 0;
	int weapon_tomahawk_delay_frames = 0;
	int weapon_tomahawk_clip_size = 0;
	int weapon_tomahawk_clip_reload_frames = 0;
	int weapon_tomahawk_damage_type = 0;
	int weapon_tomahawk_death_type = 0;
	std::string weapon_tomahawk_fire_sound;
	bool weapon_tomahawk_projectile_exhaust_loaded = false;
	bool weapon_tomahawk_heroic_projectile_exhaust_loaded = false;
	bool terrain_roads_two_lane_found = false;
	bool terrain_roads_four_lane_found = false;
	bool terrain_roads_dirt_road_found = false;
	bool terrain_roads_concrete_bridge_found = false;
	std::string terrain_roads_two_lane_texture;
	std::string terrain_roads_four_lane_texture;
	std::string terrain_roads_dirt_road_texture;
	std::string terrain_roads_concrete_bridge_texture;
	std::string terrain_roads_concrete_bridge_model;
	std::string terrain_roads_concrete_bridge_damaged_texture;
	std::string terrain_roads_concrete_bridge_scaffold;
	std::string terrain_roads_concrete_bridge_tower_left;
	std::string terrain_roads_concrete_bridge_damage_sound;
	std::string terrain_roads_concrete_bridge_repaired_sound;
	std::string terrain_roads_concrete_bridge_damage_ocl;
	std::string terrain_roads_concrete_bridge_damage_fx;
	std::string terrain_roads_concrete_bridge_repair_fx;
	float terrain_roads_two_lane_width = 0.0f;
	float terrain_roads_two_lane_width_in_texture = 0.0f;
	float terrain_roads_four_lane_width = 0.0f;
	float terrain_roads_dirt_road_width = 0.0f;
	float terrain_roads_dirt_road_width_in_texture = 0.0f;
	float terrain_roads_concrete_bridge_scale = 0.0f;
	float terrain_roads_concrete_bridge_radar_red = 0.0f;
	float terrain_roads_concrete_bridge_radar_green = 0.0f;
	float terrain_roads_concrete_bridge_radar_blue = 0.0f;
	float terrain_roads_concrete_bridge_transition_effects_height = 0.0f;
	int terrain_roads_concrete_bridge_num_fx_per_type = 0;
	std::string water_source;
	std::string water_morning_sky_texture;
	std::string water_morning_water_texture;
	std::string water_night_sky_texture;
	std::string water_night_water_texture;
	std::string water_standing_water_texture;
	int water_morning_repeat_count = 0;
	int water_night_repeat_count = 0;
	float water_morning_sky_texels_per_unit = 0.0f;
	float water_night_sky_texels_per_unit = 0.0f;
	float water_morning_u_scroll_per_ms = 0.0f;
	float water_morning_v_scroll_per_ms = 0.0f;
	float water_night_u_scroll_per_ms = 0.0f;
	float water_night_v_scroll_per_ms = 0.0f;
	float water_transparent_depth = 0.0f;
	float water_transparent_min_opacity = 0.0f;
	bool water_additive_blending = false;
	std::string weather_source;
	std::string weather_snow_texture;
	bool weather_snow_enabled = false;
	bool weather_use_point_sprites = false;
	float weather_snow_box_dimensions = 0.0f;
	float weather_snow_box_density = 0.0f;
	float weather_snow_frequency_scale_x = 0.0f;
	float weather_snow_frequency_scale_y = 0.0f;
	float weather_snow_amplitude = 0.0f;
	float weather_snow_velocity = 0.0f;
	float weather_snow_point_size = 0.0f;
	float weather_snow_quad_size = 0.0f;
	float weather_snow_max_point_size = 0.0f;
	float weather_snow_min_point_size = 0.0f;
	std::string video_source;
	std::string video_first_internal_name;
	std::string video_first_filename;
	std::string video_sample_internal_name;
	std::string video_sample_filename;
	std::string map_cache_source;
	bool map_cache_has_shell_map_md = false;
	bool map_cache_has_tournament_desert = false;
	bool map_cache_shell_map_md_display_name = false;
	bool map_cache_tournament_desert_display_name = false;
	int map_cache_shell_map_md_players = 0;
	int map_cache_tournament_desert_players = 0;
	std::string archive_path;
};

ArchiveProbeResult probe_original_archive(const char *archive_path);
