#pragma once

#include <cstddef>
#include <string>

struct RealGameDataIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	std::string shell_map_name;
	bool use_fps_limit = false;
	bool use_cloud_map = false;
	int frames_per_second_limit = 0;
	int max_shell_screens = 0;
	int max_particle_count = 0;
	float default_structure_rubble_height = 0.0f;
	float group_select_volume_base = 0.0f;
};

struct RealArmorIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool name_key_generator_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	bool no_armor_found = false;
	bool human_armor_found = false;
	bool tank_armor_found = false;
	float no_armor_explosion_damage = 0.0f;
	float no_armor_hazard_cleanup_damage = 0.0f;
	float human_crush_damage = 0.0f;
	float human_armor_piercing_damage = 0.0f;
	float human_flame_damage = 0.0f;
	float tank_small_arms_damage = 0.0f;
	float tank_radiation_damage = 0.0f;
	float tank_microwave_damage = 0.0f;
};

struct RealDamageFXIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool name_key_generator_loaded = false;
	bool fx_list_store_loaded = false;
	bool damage_fx_store_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	bool default_damage_fx_found = false;
	bool tank_damage_fx_found = false;
	bool small_tank_damage_fx_found = false;
	bool structure_damage_fx_found = false;
	bool infantry_damage_fx_found = false;
	unsigned int default_explosion_throttle = 0;
	unsigned int tank_small_arms_throttle = 0;
	unsigned int small_tank_comanche_throttle = 0;
	unsigned int structure_flame_throttle = 0;
	unsigned int infantry_sniper_throttle = 0;
};

struct RealFXListIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool name_key_generator_loaded = false;
	bool fx_list_store_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t list_count = 0;
	std::string source;
	std::string archive_path;
	bool toxin_shell_found = false;
	bool car_crusher_found = false;
	bool damage_tank_struck_found = false;
	bool moab_blast_found = false;
	bool bunker_buster_found = false;
	std::size_t toxin_shell_nuggets = 0;
	std::size_t car_crusher_nuggets = 0;
	std::size_t damage_tank_struck_nuggets = 0;
	std::size_t moab_blast_nuggets = 0;
	std::size_t bunker_buster_nuggets = 0;
};

struct RealObjectCreationListIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool default_file_exists = false;
	bool file_exists = false;
	bool fx_list_file_exists = false;
	bool weapon_file_exists = false;
	bool particle_file_exists = false;
	bool name_key_generator_loaded = false;
	bool fx_list_store_loaded = false;
	bool particle_system_manager_loaded = false;
	bool weapon_store_loaded = false;
	bool object_creation_list_store_loaded = false;
	bool fx_list_original_ini_load = false;
	bool particle_original_ini_load = false;
	bool weapon_original_ini_load = false;
	bool default_original_ini_load = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t fx_list_bytes = 0;
	std::size_t weapon_bytes = 0;
	std::size_t particle_bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t list_count = 0;
	std::size_t nugget_count = 0;
	std::string source;
	std::string archive_path;
	bool fire_wall_segment_found = false;
	bool technical_crush_found = false;
	bool daisy_cutter_found = false;
	bool scud_storm_found = false;
	bool sneak_attack_tunnel_found = false;
	std::size_t fire_wall_segment_nuggets = 0;
	std::size_t technical_crush_nuggets = 0;
	std::size_t daisy_cutter_nuggets = 0;
	std::size_t scud_storm_nuggets = 0;
	std::size_t sneak_attack_tunnel_nuggets = 0;
};

struct RealWeaponIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool particle_file_exists = false;
	bool name_key_generator_loaded = false;
	bool fx_list_store_loaded = false;
	bool particle_system_manager_loaded = false;
	bool weapon_store_loaded = false;
	bool particle_original_ini_load = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t particle_bytes = 0;
	std::size_t particle_template_count = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	bool tomahawk_exhaust_template_found = false;
	bool heroic_tomahawk_exhaust_template_found = false;
	bool ranger_found = false;
	bool crusader_found = false;
	bool tomahawk_found = false;
	float ranger_primary_damage = 0.0f;
	float ranger_attack_range = 0.0f;
	int ranger_delay_frames = 0;
	int ranger_clip_size = 0;
	int ranger_clip_reload_frames = 0;
	int ranger_damage_type = 0;
	int ranger_death_type = 0;
	std::string ranger_fire_sound;
	float crusader_primary_damage = 0.0f;
	float crusader_primary_damage_radius = 0.0f;
	float crusader_attack_range = 0.0f;
	int crusader_delay_frames = 0;
	int crusader_clip_size = 0;
	int crusader_damage_type = 0;
	int crusader_death_type = 0;
	std::string crusader_fire_sound;
	float tomahawk_primary_damage = 0.0f;
	float tomahawk_primary_damage_radius = 0.0f;
	float tomahawk_secondary_damage = 0.0f;
	float tomahawk_secondary_damage_radius = 0.0f;
	float tomahawk_attack_range = 0.0f;
	float tomahawk_minimum_attack_range = 0.0f;
	int tomahawk_pre_attack_delay_frames = 0;
	int tomahawk_delay_frames = 0;
	int tomahawk_clip_size = 0;
	int tomahawk_clip_reload_frames = 0;
	int tomahawk_damage_type = 0;
	int tomahawk_death_type = 0;
	std::string tomahawk_fire_sound;
	bool tomahawk_projectile_exhaust_loaded = false;
	bool tomahawk_heroic_projectile_exhaust_loaded = false;
};

struct RealAIDataIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool default_file_exists = false;
	bool override_file_exists = false;
	bool science_file_exists = false;
	bool science_store_loaded = false;
	bool ai_loaded = false;
	bool science_original_ini_load = false;
	bool default_original_ini_load = false;
	bool override_original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t science_bytes = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	float structure_seconds = 0.0f;
	float team_seconds = 0.0f;
	int resources_wealthy = 0;
	int resources_poor = 0;
	unsigned int force_idle_frames = 0;
	float structures_wealthy_rate = 0.0f;
	float teams_wealthy_rate = 0.0f;
	float structures_poor_rate = 0.0f;
	float teams_poor_rate = 0.0f;
	float team_resources_to_start = 0.0f;
	float guard_inner_modifier_ai = 0.0f;
	float guard_outer_modifier_ai = 0.0f;
	float guard_inner_modifier_human = 0.0f;
	float guard_outer_modifier_human = 0.0f;
	unsigned int guard_chase_unit_frames = 0;
	unsigned int guard_enemy_scan_frames = 0;
	unsigned int guard_enemy_return_scan_frames = 0;
	float attack_priority_distance_modifier = 0.0f;
	float max_recruit_radius = 0.0f;
	float skirmish_base_defense_extra_distance = 0.0f;
	float wall_height = 0.0f;
	bool attack_uses_line_of_sight = false;
	bool attack_ignore_insignificant_buildings = false;
	bool enable_repulsors = false;
	int min_infantry_for_group = 0;
	int min_vehicles_for_group = 0;
	float min_distance_for_group = 0.0f;
	float distance_requires_group = 0.0f;
	float supply_center_safe_radius = 0.0f;
	int rebuild_delay_seconds = 0;
	bool ai_crushes_infantry = false;
	std::size_t side_info_count = 0;
	std::size_t build_list_count = 0;
	bool america_side_found = false;
	int america_resource_gatherers_easy = 0;
	int america_resource_gatherers_normal = 0;
	int america_resource_gatherers_hard = 0;
	std::string america_base_defense_structure;
	std::size_t america_skill_set1_count = 0;
	std::string america_skill_set1_first_science;
	bool gla_side_found = false;
	int gla_resource_gatherers_easy = 0;
	std::string gla_base_defense_structure;
	bool america_build_list_found = false;
	std::size_t america_build_list_structure_count = 0;
	std::string america_first_build_template;
	float america_first_build_x = 0.0f;
	float america_first_build_y = 0.0f;
	float america_first_build_angle = 0.0f;
	bool america_first_build_automatically_build = false;
};

struct RealLocomotorIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool name_key_generator_loaded = false;
	bool locomotor_store_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t template_count = 0;
	std::string source;
	std::string archive_path;
	bool basic_human_found = false;
	bool missile_defender_found = false;
	bool humvee_found = false;
	bool comanche_found = false;
	float basic_human_speed = 0.0f;
	float basic_human_speed_damaged = 0.0f;
	float basic_human_turn_rate = 0.0f;
	float basic_human_acceleration = 0.0f;
	float basic_human_braking = 0.0f;
	int basic_human_surfaces = 0;
	int basic_human_appearance = 0;
	int basic_human_z_behavior = 0;
	int basic_human_move_priority = 0;
	bool basic_human_stick_to_ground = false;
	float missile_defender_speed = 0.0f;
	int missile_defender_move_priority = 0;
	float humvee_speed = 0.0f;
	float humvee_speed_damaged = 0.0f;
	float humvee_turn_rate = 0.0f;
	float humvee_acceleration = 0.0f;
	float humvee_braking = 0.0f;
	float humvee_min_turn_speed = 0.0f;
	float humvee_turn_pivot_offset = 0.0f;
	float humvee_wheel_turn_angle = 0.0f;
	float humvee_max_wheel_extension = 0.0f;
	float humvee_max_wheel_compression = 0.0f;
	int humvee_surfaces = 0;
	int humvee_appearance = 0;
	int humvee_z_behavior = 0;
	bool humvee_stick_to_ground = false;
	bool humvee_has_suspension = false;
	bool humvee_can_move_backward = false;
	float comanche_speed = 0.0f;
	float comanche_speed_damaged = 0.0f;
	float comanche_turn_rate = 0.0f;
	float comanche_acceleration = 0.0f;
	float comanche_lift = 0.0f;
	float comanche_lift_damaged = 0.0f;
	float comanche_braking = 0.0f;
	float comanche_preferred_height = 0.0f;
	int comanche_surfaces = 0;
	int comanche_appearance = 0;
	int comanche_z_behavior = 0;
	int comanche_airborne_targeting_height = 0;
	bool comanche_allow_airborne_motive_force = false;
	bool comanche_apply_2d_friction_when_airborne = false;
	bool comanche_locomotor_works_when_dead = false;
};

struct RealScienceIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool game_text_loaded = false;
	bool name_key_generator_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t science_count = 0;
	std::string source;
	std::string archive_path;
	bool america_science_found = false;
	bool rank3_science_found = false;
	bool paladin_science_found = false;
	bool paladin_name_loaded = false;
	bool paladin_description_loaded = false;
	int america_purchase_cost = 0;
	int paladin_purchase_cost = 0;
	bool america_grantable = false;
	bool paladin_grantable = false;
};

struct RealMapCacheIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool game_text_loaded = false;
	bool name_key_generator_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t map_count = 0;
	std::size_t multiplayer_count = 0;
	std::size_t official_count = 0;
	std::string source;
	std::string archive_path;
	bool has_shell_map_md = false;
	bool has_tournament_desert = false;
	bool shell_map_md_display_name = false;
	bool tournament_desert_display_name = false;
	int shell_map_md_players = 0;
	int tournament_desert_players = 0;
};

struct RealWeatherIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	std::string snow_texture;
	bool snow_enabled = false;
	bool use_point_sprites = false;
	float snow_box_dimensions = 0.0f;
	float snow_box_density = 0.0f;
	float snow_frequency_scale_x = 0.0f;
	float snow_frequency_scale_y = 0.0f;
	float snow_amplitude = 0.0f;
	float snow_velocity = 0.0f;
	float snow_point_size = 0.0f;
	float snow_quad_size = 0.0f;
	float snow_max_point_size = 0.0f;
	float snow_min_point_size = 0.0f;
};

struct RealWaterIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	bool transparency_loaded = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t water_set_count = 0;
	std::string source;
	std::string archive_path;
	std::string morning_sky_texture;
	std::string morning_water_texture;
	std::string night_sky_texture;
	std::string night_water_texture;
	std::string standing_water_texture;
	int morning_water_repeat_count = 0;
	int night_water_repeat_count = 0;
	float morning_sky_texels_per_unit = 0.0f;
	float night_sky_texels_per_unit = 0.0f;
	float morning_u_scroll_per_ms = 0.0f;
	float morning_v_scroll_per_ms = 0.0f;
	float night_u_scroll_per_ms = 0.0f;
	float night_v_scroll_per_ms = 0.0f;
	float transparent_water_depth = 0.0f;
	float transparent_water_min_opacity = 0.0f;
	bool additive_blending = false;
};

struct RealVideoIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool default_file_exists = false;
	bool original_ini_load = false;
	bool default_original_ini_load = false;
	bool shipped_original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t default_bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t video_count = 0;
	std::string source;
	std::string archive_path;
	std::string first_internal_name;
	std::string first_filename;
	std::string sample_internal_name;
	std::string sample_filename;
};

struct RealMultiplayerIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t color_count = 0;
	std::size_t starting_money_count = 0;
	std::string source;
	std::string archive_path;
	int start_countdown_seconds = 0;
	int max_beacons_per_player = 0;
	bool use_shroud = false;
	bool show_random_player_template = false;
	bool show_random_start_pos = false;
	bool show_random_color = false;
	bool gold_color_found = false;
	bool purple_color_found = false;
	unsigned int gold_color = 0;
	unsigned int purple_night_color = 0;
	unsigned int chat_default_color = 0;
	unsigned int chat_game_color = 0;
	unsigned int chat_player_normal_color = 0;
	unsigned int chat_self_color = 0;
	unsigned int chat_map_selected_color = 0;
	int starting_money_first = 0;
	int starting_money_second = 0;
	int starting_money_third = 0;
	int starting_money_fourth = 0;
	int default_starting_money = 0;
};

struct RealTerrainIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t terrain_count = 0;
	std::string source;
	std::string archive_path;
	bool transition_found = false;
	bool asphalt_found = false;
	bool desert_dry_found = false;
	bool beach_tropical_found = false;
	bool snow_flat_found = false;
	std::string transition_texture;
	std::string asphalt_texture;
	std::string desert_dry_texture;
	std::string beach_tropical_texture;
	std::string snow_flat_texture;
	int transition_class = 0;
	int asphalt_class = 0;
	int desert_dry_class = 0;
	int beach_tropical_class = 0;
	int snow_flat_class = 0;
	bool asphalt_blend_edges = false;
	bool asphalt_restrict_construction = false;
};

struct RealTerrainRoadsIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t road_count = 0;
	std::size_t bridge_count = 0;
	std::string source;
	std::string archive_path;
	bool two_lane_found = false;
	bool four_lane_found = false;
	bool dirt_road_found = false;
	bool concrete_bridge_found = false;
	std::string two_lane_texture;
	std::string four_lane_texture;
	std::string dirt_road_texture;
	std::string concrete_bridge_texture;
	std::string concrete_bridge_model;
	std::string concrete_bridge_damaged_texture;
	std::string concrete_bridge_scaffold;
	std::string concrete_bridge_tower_left;
	std::string concrete_bridge_damage_sound;
	std::string concrete_bridge_repaired_sound;
	std::string concrete_bridge_damage_ocl;
	std::string concrete_bridge_damage_fx;
	std::string concrete_bridge_repair_fx;
	float two_lane_width = 0.0f;
	float two_lane_width_in_texture = 0.0f;
	float four_lane_width = 0.0f;
	float dirt_road_width = 0.0f;
	float dirt_road_width_in_texture = 0.0f;
	float concrete_bridge_scale = 0.0f;
	float concrete_bridge_radar_red = 0.0f;
	float concrete_bridge_radar_green = 0.0f;
	float concrete_bridge_radar_blue = 0.0f;
	float concrete_bridge_transition_effects_height = 0.0f;
	int concrete_bridge_num_fx_per_type = 0;
};

struct RealDrawGroupInfoIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	std::string font_name;
	int font_size = 0;
	bool font_is_bold = false;
	bool use_player_color = false;
	unsigned int color_for_text = 0;
	unsigned int color_for_text_drop_shadow = 0;
	int drop_shadow_offset_x = 0;
	int drop_shadow_offset_y = 0;
	bool using_pixel_offset_x = false;
	bool using_pixel_offset_y = false;
	int pixel_offset_x = 0;
	int pixel_offset_y = 0;
	float percent_offset_x = 0.0f;
	float percent_offset_y = 0.0f;
};

struct RealMappedImageIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool name_key_generator_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t file_count = 0;
	std::size_t image_count = 0;
	std::string source;
	std::string archive_path;
	bool sa_chinook_found = false;
	std::string sa_chinook_texture;
	int sa_chinook_texture_width = 0;
	int sa_chinook_texture_height = 0;
	int sa_chinook_width = 0;
	int sa_chinook_height = 0;
	unsigned int sa_chinook_status = 0;
	float sa_chinook_uv_lo_x = 0.0f;
	float sa_chinook_uv_lo_y = 0.0f;
	float sa_chinook_uv_hi_x = 0.0f;
	float sa_chinook_uv_hi_y = 0.0f;
	bool watermark_china_found = false;
	std::string watermark_china_texture;
	int watermark_china_width = 0;
	int watermark_china_height = 0;
	unsigned int watermark_china_status = 0;
	bool watermark_china_rotated = false;
};

struct RealControlBarSchemeIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool default_file_exists = false;
	bool file_exists = false;
	bool name_key_generator_loaded = false;
	bool mapped_images_loaded = false;
	bool control_bar_loaded = false;
	bool original_default_ini_load = false;
	bool original_ini_load = false;
	std::size_t default_bytes = 0;
	std::size_t bytes = 0;
	std::size_t mapped_image_count = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	bool default_found = false;
	std::string default_queue_image;
	std::string default_right_hud_image;
	std::string default_base_image;
	int default_base_layer = 0;
	int default_base_width = 0;
	int default_base_height = 0;
	bool america_found = false;
	std::string america_side;
	std::string america_queue_image;
	std::string america_right_hud_image;
	std::string america_command_marker_image;
	std::string america_power_purchase_image;
	std::string america_base_image;
	int america_screen_x = 0;
	int america_screen_y = 0;
	int america_base_layer = 0;
	int america_base_x = 0;
	int america_base_y = 0;
	int america_base_width = 0;
	int america_base_height = 0;
	bool gla_found = false;
	std::string gla_side;
	std::string gla_right_hud_image;
	std::string gla_command_marker_image;
	std::string gla_power_purchase_image;
	std::string gla_base_image;
	bool china_found = false;
	std::string china_side;
	std::string china_right_hud_image;
	std::string china_command_marker_image;
	std::string china_power_purchase_image;
	std::string china_gen_arrow_image;
	std::string china_base_image;
};

struct RealCrateIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool science_file_exists = false;
	bool game_text_loaded = false;
	bool name_key_generator_loaded = false;
	bool science_original_ini_load = false;
	bool original_ini_load = false;
	bool filtered_from_shipped = false;
	std::size_t bytes = 0;
	std::size_t science_bytes = 0;
	std::size_t filtered_bytes = 0;
	std::size_t filtered_blocks = 0;
	std::size_t parsed_fields = 0;
	std::size_t crate_template_count = 0;
	std::string source;
	std::string archive_path;
	bool salvage_found = false;
	float salvage_creation_chance = 0.0f;
	bool salvage_salvager_kindof = false;
	bool salvage_killer_science_valid = false;
	std::size_t salvage_object_count = 0;
	std::string salvage_object_name;
	float salvage_object_chance = 0.0f;
	bool elite_found = false;
	float elite_creation_chance = 0.0f;
	int elite_veterancy_level = 0;
	std::size_t elite_object_count = 0;
	std::string elite_first_object;
	float elite_first_chance = 0.0f;
	std::string elite_second_object;
	float elite_second_chance = 0.0f;
	bool heroic_found = false;
	float heroic_creation_chance = 0.0f;
	int heroic_veterancy_level = 0;
	std::size_t heroic_object_count = 0;
	std::string heroic_first_object;
	float heroic_first_chance = 0.0f;
	std::string heroic_third_object;
	float heroic_third_chance = 0.0f;
	bool gla02_100_found = false;
	bool gla02_100_owned_by_maker = false;
	std::string gla02_100_object;
	float gla02_100_object_chance = 0.0f;
	bool gla02_2500_found = false;
	bool gla02_2500_owned_by_maker = false;
	std::string gla02_2500_object;
	float gla02_2500_object_chance = 0.0f;
};

struct RealUpgradeIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool name_key_generator_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t upgrade_count = 0;
	std::string source;
	std::string archive_path;
	bool veteran_found = false;
	bool elite_found = false;
	bool heroic_found = false;
	bool flash_bang_found = false;
	bool capture_building_found = false;
	bool laser_missiles_found = false;
	bool china_mines_found = false;
	bool america_radar_found = false;
	std::string flash_bang_display_name;
	std::string capture_building_display_name;
	std::string laser_missiles_display_name;
	std::string china_mines_display_name;
	std::string america_radar_display_name;
	std::string flash_bang_research_sound;
	std::string laser_missiles_research_sound;
	std::string china_mines_research_sound;
	std::string america_radar_research_sound;
	int flash_bang_type = 0;
	int capture_building_type = 0;
	int laser_missiles_type = 0;
	int china_mines_type = 0;
	int america_radar_type = 0;
	int flash_bang_build_frames = 0;
	int capture_building_build_frames = 0;
	int laser_missiles_build_frames = 0;
	int china_mines_build_frames = 0;
	int america_radar_build_frames = 0;
	int flash_bang_cost = 0;
	int capture_building_cost = 0;
	int laser_missiles_cost = 0;
	int china_mines_cost = 0;
	int america_radar_cost = 0;
	int america_radar_academy_classification = 0;
};

struct RealSpecialPowerIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool science_file_exists = false;
	bool game_text_loaded = false;
	bool name_key_generator_loaded = false;
	bool audio_manager_loaded = false;
	bool science_original_ini_load = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t science_bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t special_power_count = 0;
	std::string source;
	std::string archive_path;
	bool daisy_cutter_found = false;
	bool carpet_bomb_found = false;
	bool crate_drop_found = false;
	bool neutron_missile_found = false;
	bool scud_storm_found = false;
	int daisy_cutter_enum = 0;
	int carpet_bomb_enum = 0;
	int crate_drop_enum = 0;
	int daisy_cutter_reload_frames = 0;
	int carpet_bomb_reload_frames = 0;
	int crate_drop_reload_frames = 0;
	bool daisy_cutter_required_science_valid = false;
	bool crate_drop_required_science_valid = false;
	bool daisy_cutter_public_timer = false;
	bool carpet_bomb_public_timer = false;
	bool crate_drop_public_timer = false;
	bool daisy_cutter_shared_synced_timer = false;
	bool carpet_bomb_shared_synced_timer = false;
	bool crate_drop_shared_synced_timer = false;
	int daisy_cutter_view_object_duration_frames = 0;
	int carpet_bomb_view_object_duration_frames = 0;
	int crate_drop_view_object_duration_frames = 0;
	float daisy_cutter_view_object_range = 0.0f;
	float carpet_bomb_view_object_range = 0.0f;
	float crate_drop_view_object_range = 0.0f;
	float daisy_cutter_radius_cursor_radius = 0.0f;
	float carpet_bomb_radius_cursor_radius = 0.0f;
	float crate_drop_radius_cursor_radius = 0.0f;
	bool daisy_cutter_shortcut_power = false;
	bool carpet_bomb_shortcut_power = false;
	bool crate_drop_shortcut_power = false;
	int daisy_cutter_academy_classification = 0;
	int carpet_bomb_academy_classification = 0;
	std::string daisy_cutter_required_science;
	std::string crate_drop_required_science;
	std::string neutron_missile_initiate_at_location_sound;
	std::string scud_storm_initiate_sound;
};

struct RealCommandButtonIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool science_file_exists = false;
	bool special_power_file_exists = false;
	bool upgrade_file_exists = false;
	bool name_key_generator_loaded = false;
	bool science_original_ini_load = false;
	bool special_power_original_ini_load = false;
	bool upgrade_original_ini_load = false;
	bool original_ini_load = false;
	bool filtered_from_shipped = false;
	bool special_power_option_pairing_valid = false;
	std::size_t bytes = 0;
	std::size_t science_bytes = 0;
	std::size_t special_power_bytes = 0;
	std::size_t upgrade_bytes = 0;
	std::size_t filtered_bytes = 0;
	std::size_t filtered_blocks = 0;
	std::size_t parsed_fields = 0;
	std::size_t button_count = 0;
	std::string source;
	std::string archive_path;
	bool flash_bang_upgrade_found = false;
	int flash_bang_upgrade_command = 0;
	int flash_bang_upgrade_border = 0;
	std::string flash_bang_upgrade_name;
	std::string flash_bang_upgrade_label;
	std::string flash_bang_upgrade_description;
	bool ranger_capture_found = false;
	int ranger_capture_command = 0;
	unsigned int ranger_capture_options = 0;
	int ranger_capture_border = 0;
	std::string ranger_capture_upgrade_name;
	std::string ranger_capture_special_power_name;
	std::string ranger_capture_label;
	std::string ranger_capture_description;
	std::string ranger_capture_cursor;
	std::string ranger_capture_invalid_cursor;
	bool ranger_capture_has_enemy_target = false;
	bool ranger_capture_has_neutral_target = false;
	bool ranger_capture_has_multi_select = false;
	bool ranger_capture_has_need_upgrade = false;
	bool ranger_capture_has_need_special_power_science = false;
	bool flash_bang_switch_found = false;
	int flash_bang_switch_command = 0;
	unsigned int flash_bang_switch_options = 0;
	int flash_bang_switch_weapon_slot = 0;
	int flash_bang_switch_border = 0;
	std::string flash_bang_switch_upgrade_name;
	std::string flash_bang_switch_label;
	std::string flash_bang_switch_description;
	bool flash_bang_switch_has_check_like = false;
	bool flash_bang_switch_has_multi_select = false;
	bool flash_bang_switch_has_need_upgrade = false;
};

struct RealCommandSetIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool command_button_file_exists = false;
	bool special_power_file_exists = false;
	bool upgrade_file_exists = false;
	bool name_key_generator_loaded = false;
	bool special_power_original_ini_load = false;
	bool upgrade_original_ini_load = false;
	bool command_button_original_ini_load = false;
	bool original_ini_load = false;
	bool filtered_from_shipped = false;
	std::size_t bytes = 0;
	std::size_t command_button_bytes = 0;
	std::size_t special_power_bytes = 0;
	std::size_t upgrade_bytes = 0;
	std::size_t filtered_command_button_bytes = 0;
	std::size_t filtered_command_button_blocks = 0;
	std::size_t filtered_command_set_bytes = 0;
	std::size_t filtered_command_set_blocks = 0;
	std::size_t parsed_fields = 0;
	std::size_t command_button_count = 0;
	std::size_t command_set_count = 0;
	std::string source;
	std::string archive_path;
	bool ranger_set_found = false;
	std::string ranger_slot1;
	std::string ranger_slot2;
	std::string ranger_slot4;
	std::string ranger_slot11;
	std::string ranger_slot13;
	std::string ranger_slot14;
	int ranger_slot1_command = 0;
	int ranger_slot2_command = 0;
	int ranger_slot4_command = 0;
	int ranger_slot11_command = 0;
	int ranger_slot13_command = 0;
	int ranger_slot14_command = 0;
	int ranger_slot2_weapon_slot = 0;
	int ranger_slot4_weapon_slot = 0;
	std::string ranger_slot1_special_power;
	std::string ranger_slot1_upgrade;
	std::string ranger_slot4_upgrade;
};

struct RealPlayerTemplateIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool science_file_exists = false;
	bool game_text_loaded = false;
	bool name_key_generator_loaded = false;
	bool science_original_ini_load = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t science_bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t player_template_count = 0;
	std::size_t side_count = 0;
	std::string source;
	std::string archive_path;
	bool america_found = false;
	bool china_found = false;
	bool gla_found = false;
	bool observer_found = false;
	bool air_force_found = false;
	bool boss_found = false;
	bool america_display_name_loaded = false;
	std::string america_side;
	std::string america_base_side;
	bool america_playable = false;
	bool america_old_faction = false;
	int america_start_money = 0;
	std::size_t america_intrinsic_science_count = 0;
	bool america_intrinsic_science_valid = false;
	std::string america_starting_building;
	std::string america_starting_unit0;
	std::string america_shortcut_command_set;
	std::string america_shortcut_win_name;
	int america_shortcut_button_count = 0;
	std::string america_load_screen;
	std::string america_score_screen;
	std::string america_load_music;
	std::string america_score_music;
	std::string america_beacon;
	bool observer_is_observer = false;
	bool observer_playable = false;
	std::string observer_side;
	std::string observer_load_screen;
	std::string observer_beacon;
	std::string air_force_side;
	std::string air_force_base_side;
	bool air_force_playable = false;
	bool air_force_old_faction = false;
	std::string air_force_starting_building;
	std::string air_force_starting_unit0;
	std::string air_force_shortcut_command_set;
	int air_force_shortcut_button_count = 0;
	std::string boss_side;
	std::string boss_base_side;
	bool boss_playable = false;
	bool boss_old_faction = false;
	std::size_t boss_intrinsic_science_count = 0;
	bool boss_intrinsic_sciences_valid = false;
	std::string boss_starting_building;
	std::string boss_starting_unit0;
	std::string boss_shortcut_command_set;
	std::string boss_shortcut_win_name;
	int boss_shortcut_button_count = 0;
};

RealGameDataIniProbeResult probe_original_game_data_ini_load(const char *archive_path);
RealArmorIniProbeResult probe_original_armor_ini_load(const char *archive_path);
RealDamageFXIniProbeResult probe_original_damage_fx_ini_load(const char *archive_path);
RealFXListIniProbeResult probe_original_fx_list_ini_load(const char *archive_path);
RealObjectCreationListIniProbeResult probe_original_object_creation_list_ini_load(const char *archive_path);
RealWeaponIniProbeResult probe_original_weapon_ini_load(const char *archive_path);
RealAIDataIniProbeResult probe_original_ai_data_ini_load(const char *archive_path);
RealLocomotorIniProbeResult probe_original_locomotor_ini_load(const char *archive_path);
RealScienceIniProbeResult probe_original_science_ini_load(const char *archive_path);
RealMapCacheIniProbeResult probe_original_map_cache_ini_load(const char *archive_path);
RealWeatherIniProbeResult probe_original_weather_ini_load(const char *archive_path);
RealWaterIniProbeResult probe_original_water_ini_load(const char *archive_path);
RealVideoIniProbeResult probe_original_video_ini_load(const char *archive_path);
RealMultiplayerIniProbeResult probe_original_multiplayer_ini_load(const char *archive_path);
RealTerrainIniProbeResult probe_original_terrain_ini_load(const char *archive_path);
RealTerrainRoadsIniProbeResult probe_original_terrain_roads_ini_load(const char *archive_path);
RealDrawGroupInfoIniProbeResult probe_original_draw_group_info_ini_load(const char *archive_path);
RealMappedImageIniProbeResult probe_original_mapped_image_ini_load(const char *archive_path);
RealControlBarSchemeIniProbeResult probe_original_control_bar_scheme_ini_load(const char *archive_path);
RealCrateIniProbeResult probe_original_crate_ini_load(const char *archive_path);
RealUpgradeIniProbeResult probe_original_upgrade_ini_load(const char *archive_path);
RealSpecialPowerIniProbeResult probe_original_special_power_ini_load(const char *archive_path);
RealCommandButtonIniProbeResult probe_original_command_button_ini_load(const char *archive_path);
RealCommandSetIniProbeResult probe_original_command_set_ini_load(const char *archive_path);
RealPlayerTemplateIniProbeResult probe_original_player_template_ini_load(const char *archive_path);
