#pragma once

#include <cstddef>
#include <string>

struct ArchiveProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded = false;
	bool has_armor_ini = false;
	bool has_command_button_ini = false;
	bool has_player_template_ini = false;
	bool has_game_data_ini = false;
	bool has_science_ini = false;
	bool has_special_power_ini = false;
	bool has_multiplayer_ini = false;
	bool has_terrain_ini = false;
	bool has_roads_ini = false;
	bool has_weapon_ini = false;
	bool has_map_cache_ini = false;
	bool has_water_ini = false;
	bool has_weather_ini = false;
	bool has_video_ini = false;
	bool has_default_video_ini = false;
	bool armor_attempted = false;
	bool armor_ok = false;
	bool armor_loaded_archives = false;
	bool armor_file_exists = false;
	bool armor_name_key_generator_loaded = false;
	bool armor_original_ini_load = false;
	bool science_attempted = false;
	bool science_ok = false;
	bool science_loaded_archives = false;
	bool science_file_exists = false;
	bool science_game_text_loaded = false;
	bool science_name_key_generator_loaded = false;
	bool science_original_ini_load = false;
	bool special_power_attempted = false;
	bool special_power_ok = false;
	bool special_power_loaded_archives = false;
	bool special_power_file_exists = false;
	bool special_power_science_file_exists = false;
	bool special_power_game_text_loaded = false;
	bool special_power_name_key_generator_loaded = false;
	bool special_power_audio_manager_loaded = false;
	bool special_power_science_original_ini_load = false;
	bool special_power_original_ini_load = false;
	bool player_template_attempted = false;
	bool player_template_ok = false;
	bool player_template_loaded_archives = false;
	bool player_template_file_exists = false;
	bool player_template_science_file_exists = false;
	bool player_template_game_text_loaded = false;
	bool player_template_name_key_generator_loaded = false;
	bool player_template_science_original_ini_load = false;
	bool player_template_original_ini_load = false;
	bool game_data_attempted = false;
	bool game_data_ok = false;
	bool game_data_loaded_archives = false;
	bool game_data_file_exists = false;
	bool game_data_original_ini_load = false;
	bool multiplayer_attempted = false;
	bool multiplayer_ok = false;
	bool multiplayer_loaded_archives = false;
	bool multiplayer_file_exists = false;
	bool multiplayer_original_ini_load = false;
	bool terrain_attempted = false;
	bool terrain_ok = false;
	bool terrain_loaded_archives = false;
	bool terrain_file_exists = false;
	bool terrain_original_ini_load = false;
	bool terrain_roads_attempted = false;
	bool terrain_roads_ok = false;
	bool terrain_roads_loaded_archives = false;
	bool terrain_roads_file_exists = false;
	bool terrain_roads_original_ini_load = false;
	bool water_attempted = false;
	bool water_ok = false;
	bool water_loaded_archives = false;
	bool water_file_exists = false;
	bool water_original_ini_load = false;
	bool water_transparency_loaded = false;
	bool weather_attempted = false;
	bool weather_ok = false;
	bool weather_loaded_archives = false;
	bool weather_file_exists = false;
	bool weather_original_ini_load = false;
	bool video_attempted = false;
	bool video_ok = false;
	bool video_loaded_archives = false;
	bool video_file_exists = false;
	bool video_default_file_exists = false;
	bool video_original_ini_load = false;
	bool video_default_original_ini_load = false;
	bool video_shipped_original_ini_load = false;
	bool map_cache_attempted = false;
	bool map_cache_ok = false;
	bool map_cache_loaded_archives = false;
	bool map_cache_file_exists = false;
	bool map_cache_game_text_loaded = false;
	bool map_cache_name_key_generator_loaded = false;
	bool map_cache_original_ini_load = false;
	bool has_generals_csf = false;
	bool game_text_attempted = false;
	bool game_text_ok = false;
	bool game_text_title_label = false;
	bool game_text_control_bar_label = false;
	std::size_t indexed_file_count = 0;
	std::size_t sample_bytes = 0;
	std::size_t armor_bytes = 0;
	std::size_t armor_parsed_fields = 0;
	std::size_t science_bytes = 0;
	std::size_t science_parsed_fields = 0;
	std::size_t science_count = 0;
	std::size_t special_power_bytes = 0;
	std::size_t special_power_science_bytes = 0;
	std::size_t special_power_parsed_fields = 0;
	std::size_t special_power_count = 0;
	std::size_t player_template_bytes = 0;
	std::size_t player_template_science_bytes = 0;
	std::size_t player_template_parsed_fields = 0;
	std::size_t player_template_count = 0;
	std::size_t player_template_side_count = 0;
	std::size_t game_data_bytes = 0;
	std::size_t game_data_parsed_fields = 0;
	std::size_t multiplayer_bytes = 0;
	std::size_t multiplayer_parsed_fields = 0;
	std::size_t multiplayer_color_count = 0;
	std::size_t multiplayer_starting_money_count = 0;
	std::size_t terrain_bytes = 0;
	std::size_t terrain_parsed_fields = 0;
	std::size_t terrain_count = 0;
	std::size_t terrain_roads_bytes = 0;
	std::size_t terrain_roads_parsed_fields = 0;
	std::size_t terrain_roads_road_count = 0;
	std::size_t terrain_roads_bridge_count = 0;
	std::size_t water_bytes = 0;
	std::size_t water_parsed_fields = 0;
	std::size_t water_set_count = 0;
	std::size_t weather_bytes = 0;
	std::size_t weather_parsed_fields = 0;
	std::size_t video_bytes = 0;
	std::size_t video_default_bytes = 0;
	std::size_t video_parsed_fields = 0;
	std::size_t video_count = 0;
	std::size_t map_cache_bytes = 0;
	std::size_t map_cache_maps = 0;
	std::size_t map_cache_multiplayer_maps = 0;
	std::size_t map_cache_official_maps = 0;
	std::size_t game_text_control_bar_label_count = 0;
	std::string game_data_shell_map_name;
	std::string armor_source;
	std::string science_source;
	std::string special_power_source;
	std::string player_template_source;
	bool armor_no_armor_found = false;
	bool armor_human_armor_found = false;
	bool armor_tank_armor_found = false;
	float armor_no_armor_explosion_damage = 0.0f;
	float armor_no_armor_hazard_cleanup_damage = 0.0f;
	float armor_human_crush_damage = 0.0f;
	float armor_human_armor_piercing_damage = 0.0f;
	float armor_human_flame_damage = 0.0f;
	float armor_tank_small_arms_damage = 0.0f;
	float armor_tank_radiation_damage = 0.0f;
	float armor_tank_microwave_damage = 0.0f;
	bool science_america_found = false;
	bool science_rank3_found = false;
	bool science_paladin_found = false;
	bool science_paladin_name_loaded = false;
	bool science_paladin_description_loaded = false;
	int science_america_purchase_cost = 0;
	int science_paladin_purchase_cost = 0;
	bool science_america_grantable = false;
	bool science_paladin_grantable = false;
	bool special_power_daisy_cutter_found = false;
	bool special_power_carpet_bomb_found = false;
	bool special_power_crate_drop_found = false;
	bool special_power_neutron_missile_found = false;
	bool special_power_scud_storm_found = false;
	int special_power_daisy_cutter_enum = 0;
	int special_power_carpet_bomb_enum = 0;
	int special_power_crate_drop_enum = 0;
	int special_power_daisy_cutter_reload_frames = 0;
	int special_power_carpet_bomb_reload_frames = 0;
	int special_power_crate_drop_reload_frames = 0;
	bool special_power_daisy_cutter_required_science_valid = false;
	bool special_power_crate_drop_required_science_valid = false;
	bool special_power_daisy_cutter_public_timer = false;
	bool special_power_carpet_bomb_public_timer = false;
	bool special_power_crate_drop_public_timer = false;
	bool special_power_daisy_cutter_shared_synced_timer = false;
	bool special_power_carpet_bomb_shared_synced_timer = false;
	bool special_power_crate_drop_shared_synced_timer = false;
	int special_power_daisy_cutter_view_object_duration_frames = 0;
	int special_power_carpet_bomb_view_object_duration_frames = 0;
	int special_power_crate_drop_view_object_duration_frames = 0;
	float special_power_daisy_cutter_view_object_range = 0.0f;
	float special_power_carpet_bomb_view_object_range = 0.0f;
	float special_power_crate_drop_view_object_range = 0.0f;
	float special_power_daisy_cutter_radius_cursor_radius = 0.0f;
	float special_power_carpet_bomb_radius_cursor_radius = 0.0f;
	float special_power_crate_drop_radius_cursor_radius = 0.0f;
	bool special_power_daisy_cutter_shortcut_power = false;
	bool special_power_carpet_bomb_shortcut_power = false;
	bool special_power_crate_drop_shortcut_power = false;
	int special_power_daisy_cutter_academy_classification = 0;
	int special_power_carpet_bomb_academy_classification = 0;
	std::string special_power_daisy_cutter_required_science;
	std::string special_power_crate_drop_required_science;
	std::string special_power_neutron_missile_initiate_at_location_sound;
	std::string special_power_scud_storm_initiate_sound;
	bool player_template_america_found = false;
	bool player_template_china_found = false;
	bool player_template_gla_found = false;
	bool player_template_observer_found = false;
	bool player_template_air_force_found = false;
	bool player_template_boss_found = false;
	bool player_template_america_display_name_loaded = false;
	std::string player_template_america_side;
	std::string player_template_america_base_side;
	bool player_template_america_playable = false;
	bool player_template_america_old_faction = false;
	int player_template_america_start_money = 0;
	std::size_t player_template_america_intrinsic_science_count = 0;
	bool player_template_america_intrinsic_science_valid = false;
	std::string player_template_america_starting_building;
	std::string player_template_america_starting_unit0;
	std::string player_template_america_shortcut_command_set;
	std::string player_template_america_shortcut_win_name;
	int player_template_america_shortcut_button_count = 0;
	std::string player_template_america_load_screen;
	std::string player_template_america_score_screen;
	std::string player_template_america_load_music;
	std::string player_template_america_score_music;
	std::string player_template_america_beacon;
	bool player_template_observer_is_observer = false;
	bool player_template_observer_playable = false;
	std::string player_template_observer_side;
	std::string player_template_observer_load_screen;
	std::string player_template_observer_beacon;
	std::string player_template_air_force_side;
	std::string player_template_air_force_base_side;
	bool player_template_air_force_playable = false;
	bool player_template_air_force_old_faction = false;
	std::string player_template_air_force_starting_building;
	std::string player_template_air_force_starting_unit0;
	std::string player_template_air_force_shortcut_command_set;
	int player_template_air_force_shortcut_button_count = 0;
	std::string player_template_boss_side;
	std::string player_template_boss_base_side;
	bool player_template_boss_playable = false;
	bool player_template_boss_old_faction = false;
	std::size_t player_template_boss_intrinsic_science_count = 0;
	bool player_template_boss_intrinsic_sciences_valid = false;
	std::string player_template_boss_starting_building;
	std::string player_template_boss_starting_unit0;
	std::string player_template_boss_shortcut_command_set;
	std::string player_template_boss_shortcut_win_name;
	int player_template_boss_shortcut_button_count = 0;
	bool game_data_use_fps_limit = false;
	bool game_data_use_cloud_map = false;
	int game_data_frames_per_second_limit = 0;
	int game_data_max_shell_screens = 0;
	int game_data_max_particle_count = 0;
	float game_data_default_structure_rubble_height = 0.0f;
	float game_data_group_select_volume_base = 0.0f;
	std::string game_data_source;
	std::string multiplayer_source;
	int multiplayer_start_countdown_seconds = 0;
	int multiplayer_max_beacons_per_player = 0;
	bool multiplayer_use_shroud = false;
	bool multiplayer_show_random_player_template = false;
	bool multiplayer_show_random_start_pos = false;
	bool multiplayer_show_random_color = false;
	bool multiplayer_gold_color_found = false;
	bool multiplayer_purple_color_found = false;
	unsigned int multiplayer_gold_color = 0;
	unsigned int multiplayer_purple_night_color = 0;
	unsigned int multiplayer_chat_default_color = 0;
	unsigned int multiplayer_chat_game_color = 0;
	unsigned int multiplayer_chat_player_normal_color = 0;
	unsigned int multiplayer_chat_self_color = 0;
	unsigned int multiplayer_chat_map_selected_color = 0;
	int multiplayer_starting_money_first = 0;
	int multiplayer_starting_money_second = 0;
	int multiplayer_starting_money_third = 0;
	int multiplayer_starting_money_fourth = 0;
	int multiplayer_default_starting_money = 0;
	std::string terrain_source;
	bool terrain_transition_found = false;
	bool terrain_asphalt_found = false;
	bool terrain_desert_dry_found = false;
	bool terrain_beach_tropical_found = false;
	bool terrain_snow_flat_found = false;
	std::string terrain_transition_texture;
	std::string terrain_asphalt_texture;
	std::string terrain_desert_dry_texture;
	std::string terrain_beach_tropical_texture;
	std::string terrain_snow_flat_texture;
	int terrain_transition_class = 0;
	int terrain_asphalt_class = 0;
	int terrain_desert_dry_class = 0;
	int terrain_beach_tropical_class = 0;
	int terrain_snow_flat_class = 0;
	bool terrain_asphalt_blend_edges = false;
	bool terrain_asphalt_restrict_construction = false;
	std::string terrain_roads_source;
	bool terrain_roads_two_lane_found = false;
	bool terrain_roads_four_lane_found = false;
	bool terrain_roads_dirt_road_found = false;
	bool terrain_roads_concrete_bridge_found = false;
	std::string terrain_roads_two_lane_texture;
	std::string terrain_roads_four_lane_texture;
	std::string terrain_roads_dirt_road_texture;
	std::string terrain_roads_concrete_bridge_texture;
	std::string terrain_roads_concrete_bridge_model;
	std::string terrain_roads_concrete_bridge_damaged_texture;
	std::string terrain_roads_concrete_bridge_scaffold;
	std::string terrain_roads_concrete_bridge_tower_left;
	std::string terrain_roads_concrete_bridge_damage_sound;
	std::string terrain_roads_concrete_bridge_repaired_sound;
	std::string terrain_roads_concrete_bridge_damage_ocl;
	std::string terrain_roads_concrete_bridge_damage_fx;
	std::string terrain_roads_concrete_bridge_repair_fx;
	float terrain_roads_two_lane_width = 0.0f;
	float terrain_roads_two_lane_width_in_texture = 0.0f;
	float terrain_roads_four_lane_width = 0.0f;
	float terrain_roads_dirt_road_width = 0.0f;
	float terrain_roads_dirt_road_width_in_texture = 0.0f;
	float terrain_roads_concrete_bridge_scale = 0.0f;
	float terrain_roads_concrete_bridge_radar_red = 0.0f;
	float terrain_roads_concrete_bridge_radar_green = 0.0f;
	float terrain_roads_concrete_bridge_radar_blue = 0.0f;
	float terrain_roads_concrete_bridge_transition_effects_height = 0.0f;
	int terrain_roads_concrete_bridge_num_fx_per_type = 0;
	std::string water_source;
	std::string water_morning_sky_texture;
	std::string water_morning_water_texture;
	std::string water_night_sky_texture;
	std::string water_night_water_texture;
	std::string water_standing_water_texture;
	int water_morning_repeat_count = 0;
	int water_night_repeat_count = 0;
	float water_morning_sky_texels_per_unit = 0.0f;
	float water_night_sky_texels_per_unit = 0.0f;
	float water_morning_u_scroll_per_ms = 0.0f;
	float water_morning_v_scroll_per_ms = 0.0f;
	float water_night_u_scroll_per_ms = 0.0f;
	float water_night_v_scroll_per_ms = 0.0f;
	float water_transparent_depth = 0.0f;
	float water_transparent_min_opacity = 0.0f;
	bool water_additive_blending = false;
	std::string weather_source;
	std::string weather_snow_texture;
	bool weather_snow_enabled = false;
	bool weather_use_point_sprites = false;
	float weather_snow_box_dimensions = 0.0f;
	float weather_snow_box_density = 0.0f;
	float weather_snow_frequency_scale_x = 0.0f;
	float weather_snow_frequency_scale_y = 0.0f;
	float weather_snow_amplitude = 0.0f;
	float weather_snow_velocity = 0.0f;
	float weather_snow_point_size = 0.0f;
	float weather_snow_quad_size = 0.0f;
	float weather_snow_max_point_size = 0.0f;
	float weather_snow_min_point_size = 0.0f;
	std::string video_source;
	std::string video_first_internal_name;
	std::string video_first_filename;
	std::string video_sample_internal_name;
	std::string video_sample_filename;
	std::string map_cache_source;
	bool map_cache_has_shell_map_md = false;
	bool map_cache_has_tournament_desert = false;
	bool map_cache_shell_map_md_display_name = false;
	bool map_cache_tournament_desert_display_name = false;
	int map_cache_shell_map_md_players = 0;
	int map_cache_tournament_desert_players = 0;
	std::string archive_path;
};

ArchiveProbeResult probe_original_archive(const char *archive_path);
