#pragma once

#include <cstddef>
#include <string>

struct RealGameDataIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	std::string shell_map_name;
	bool use_fps_limit = false;
	bool use_cloud_map = false;
	int frames_per_second_limit = 0;
	int max_shell_screens = 0;
	int max_particle_count = 0;
	float default_structure_rubble_height = 0.0f;
	float group_select_volume_base = 0.0f;
};

struct RealArmorIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool name_key_generator_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	bool no_armor_found = false;
	bool human_armor_found = false;
	bool tank_armor_found = false;
	float no_armor_explosion_damage = 0.0f;
	float no_armor_hazard_cleanup_damage = 0.0f;
	float human_crush_damage = 0.0f;
	float human_armor_piercing_damage = 0.0f;
	float human_flame_damage = 0.0f;
	float tank_small_arms_damage = 0.0f;
	float tank_radiation_damage = 0.0f;
	float tank_microwave_damage = 0.0f;
};

struct RealScienceIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool game_text_loaded = false;
	bool name_key_generator_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t science_count = 0;
	std::string source;
	std::string archive_path;
	bool america_science_found = false;
	bool rank3_science_found = false;
	bool paladin_science_found = false;
	bool paladin_name_loaded = false;
	bool paladin_description_loaded = false;
	int america_purchase_cost = 0;
	int paladin_purchase_cost = 0;
	bool america_grantable = false;
	bool paladin_grantable = false;
};

struct RealMapCacheIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool game_text_loaded = false;
	bool name_key_generator_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t map_count = 0;
	std::size_t multiplayer_count = 0;
	std::size_t official_count = 0;
	std::string source;
	std::string archive_path;
	bool has_shell_map_md = false;
	bool has_tournament_desert = false;
	bool shell_map_md_display_name = false;
	bool tournament_desert_display_name = false;
	int shell_map_md_players = 0;
	int tournament_desert_players = 0;
};

struct RealWeatherIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	std::string snow_texture;
	bool snow_enabled = false;
	bool use_point_sprites = false;
	float snow_box_dimensions = 0.0f;
	float snow_box_density = 0.0f;
	float snow_frequency_scale_x = 0.0f;
	float snow_frequency_scale_y = 0.0f;
	float snow_amplitude = 0.0f;
	float snow_velocity = 0.0f;
	float snow_point_size = 0.0f;
	float snow_quad_size = 0.0f;
	float snow_max_point_size = 0.0f;
	float snow_min_point_size = 0.0f;
};

struct RealWaterIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	bool transparency_loaded = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t water_set_count = 0;
	std::string source;
	std::string archive_path;
	std::string morning_sky_texture;
	std::string morning_water_texture;
	std::string night_sky_texture;
	std::string night_water_texture;
	std::string standing_water_texture;
	int morning_water_repeat_count = 0;
	int night_water_repeat_count = 0;
	float morning_sky_texels_per_unit = 0.0f;
	float night_sky_texels_per_unit = 0.0f;
	float morning_u_scroll_per_ms = 0.0f;
	float morning_v_scroll_per_ms = 0.0f;
	float night_u_scroll_per_ms = 0.0f;
	float night_v_scroll_per_ms = 0.0f;
	float transparent_water_depth = 0.0f;
	float transparent_water_min_opacity = 0.0f;
	bool additive_blending = false;
};

struct RealVideoIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool default_file_exists = false;
	bool original_ini_load = false;
	bool default_original_ini_load = false;
	bool shipped_original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t default_bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t video_count = 0;
	std::string source;
	std::string archive_path;
	std::string first_internal_name;
	std::string first_filename;
	std::string sample_internal_name;
	std::string sample_filename;
};

struct RealMultiplayerIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t color_count = 0;
	std::size_t starting_money_count = 0;
	std::string source;
	std::string archive_path;
	int start_countdown_seconds = 0;
	int max_beacons_per_player = 0;
	bool use_shroud = false;
	bool show_random_player_template = false;
	bool show_random_start_pos = false;
	bool show_random_color = false;
	bool gold_color_found = false;
	bool purple_color_found = false;
	unsigned int gold_color = 0;
	unsigned int purple_night_color = 0;
	unsigned int chat_default_color = 0;
	unsigned int chat_game_color = 0;
	unsigned int chat_player_normal_color = 0;
	unsigned int chat_self_color = 0;
	unsigned int chat_map_selected_color = 0;
	int starting_money_first = 0;
	int starting_money_second = 0;
	int starting_money_third = 0;
	int starting_money_fourth = 0;
	int default_starting_money = 0;
};

struct RealTerrainIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t terrain_count = 0;
	std::string source;
	std::string archive_path;
	bool transition_found = false;
	bool asphalt_found = false;
	bool desert_dry_found = false;
	bool beach_tropical_found = false;
	bool snow_flat_found = false;
	std::string transition_texture;
	std::string asphalt_texture;
	std::string desert_dry_texture;
	std::string beach_tropical_texture;
	std::string snow_flat_texture;
	int transition_class = 0;
	int asphalt_class = 0;
	int desert_dry_class = 0;
	int beach_tropical_class = 0;
	int snow_flat_class = 0;
	bool asphalt_blend_edges = false;
	bool asphalt_restrict_construction = false;
};

struct RealTerrainRoadsIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t road_count = 0;
	std::size_t bridge_count = 0;
	std::string source;
	std::string archive_path;
	bool two_lane_found = false;
	bool four_lane_found = false;
	bool dirt_road_found = false;
	bool concrete_bridge_found = false;
	std::string two_lane_texture;
	std::string four_lane_texture;
	std::string dirt_road_texture;
	std::string concrete_bridge_texture;
	std::string concrete_bridge_model;
	std::string concrete_bridge_damaged_texture;
	std::string concrete_bridge_scaffold;
	std::string concrete_bridge_tower_left;
	std::string concrete_bridge_damage_sound;
	std::string concrete_bridge_repaired_sound;
	std::string concrete_bridge_damage_ocl;
	std::string concrete_bridge_damage_fx;
	std::string concrete_bridge_repair_fx;
	float two_lane_width = 0.0f;
	float two_lane_width_in_texture = 0.0f;
	float four_lane_width = 0.0f;
	float dirt_road_width = 0.0f;
	float dirt_road_width_in_texture = 0.0f;
	float concrete_bridge_scale = 0.0f;
	float concrete_bridge_radar_red = 0.0f;
	float concrete_bridge_radar_green = 0.0f;
	float concrete_bridge_radar_blue = 0.0f;
	float concrete_bridge_transition_effects_height = 0.0f;
	int concrete_bridge_num_fx_per_type = 0;
};

struct RealDrawGroupInfoIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::string source;
	std::string archive_path;
	std::string font_name;
	int font_size = 0;
	bool font_is_bold = false;
	bool use_player_color = false;
	unsigned int color_for_text = 0;
	unsigned int color_for_text_drop_shadow = 0;
	int drop_shadow_offset_x = 0;
	int drop_shadow_offset_y = 0;
	bool using_pixel_offset_x = false;
	bool using_pixel_offset_y = false;
	int pixel_offset_x = 0;
	int pixel_offset_y = 0;
	float percent_offset_x = 0.0f;
	float percent_offset_y = 0.0f;
};

struct RealUpgradeIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool name_key_generator_loaded = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t upgrade_count = 0;
	std::string source;
	std::string archive_path;
	bool veteran_found = false;
	bool elite_found = false;
	bool heroic_found = false;
	bool flash_bang_found = false;
	bool capture_building_found = false;
	bool laser_missiles_found = false;
	bool china_mines_found = false;
	bool america_radar_found = false;
	std::string flash_bang_display_name;
	std::string capture_building_display_name;
	std::string laser_missiles_display_name;
	std::string china_mines_display_name;
	std::string america_radar_display_name;
	std::string flash_bang_research_sound;
	std::string laser_missiles_research_sound;
	std::string china_mines_research_sound;
	std::string america_radar_research_sound;
	int flash_bang_type = 0;
	int capture_building_type = 0;
	int laser_missiles_type = 0;
	int china_mines_type = 0;
	int america_radar_type = 0;
	int flash_bang_build_frames = 0;
	int capture_building_build_frames = 0;
	int laser_missiles_build_frames = 0;
	int china_mines_build_frames = 0;
	int america_radar_build_frames = 0;
	int flash_bang_cost = 0;
	int capture_building_cost = 0;
	int laser_missiles_cost = 0;
	int china_mines_cost = 0;
	int america_radar_cost = 0;
	int america_radar_academy_classification = 0;
};

struct RealSpecialPowerIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool science_file_exists = false;
	bool game_text_loaded = false;
	bool name_key_generator_loaded = false;
	bool audio_manager_loaded = false;
	bool science_original_ini_load = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t science_bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t special_power_count = 0;
	std::string source;
	std::string archive_path;
	bool daisy_cutter_found = false;
	bool carpet_bomb_found = false;
	bool crate_drop_found = false;
	bool neutron_missile_found = false;
	bool scud_storm_found = false;
	int daisy_cutter_enum = 0;
	int carpet_bomb_enum = 0;
	int crate_drop_enum = 0;
	int daisy_cutter_reload_frames = 0;
	int carpet_bomb_reload_frames = 0;
	int crate_drop_reload_frames = 0;
	bool daisy_cutter_required_science_valid = false;
	bool crate_drop_required_science_valid = false;
	bool daisy_cutter_public_timer = false;
	bool carpet_bomb_public_timer = false;
	bool crate_drop_public_timer = false;
	bool daisy_cutter_shared_synced_timer = false;
	bool carpet_bomb_shared_synced_timer = false;
	bool crate_drop_shared_synced_timer = false;
	int daisy_cutter_view_object_duration_frames = 0;
	int carpet_bomb_view_object_duration_frames = 0;
	int crate_drop_view_object_duration_frames = 0;
	float daisy_cutter_view_object_range = 0.0f;
	float carpet_bomb_view_object_range = 0.0f;
	float crate_drop_view_object_range = 0.0f;
	float daisy_cutter_radius_cursor_radius = 0.0f;
	float carpet_bomb_radius_cursor_radius = 0.0f;
	float crate_drop_radius_cursor_radius = 0.0f;
	bool daisy_cutter_shortcut_power = false;
	bool carpet_bomb_shortcut_power = false;
	bool crate_drop_shortcut_power = false;
	int daisy_cutter_academy_classification = 0;
	int carpet_bomb_academy_classification = 0;
	std::string daisy_cutter_required_science;
	std::string crate_drop_required_science;
	std::string neutron_missile_initiate_at_location_sound;
	std::string scud_storm_initiate_sound;
};

struct RealCommandButtonIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool science_file_exists = false;
	bool special_power_file_exists = false;
	bool upgrade_file_exists = false;
	bool name_key_generator_loaded = false;
	bool science_original_ini_load = false;
	bool special_power_original_ini_load = false;
	bool upgrade_original_ini_load = false;
	bool original_ini_load = false;
	bool filtered_from_shipped = false;
	bool special_power_option_pairing_valid = false;
	std::size_t bytes = 0;
	std::size_t science_bytes = 0;
	std::size_t special_power_bytes = 0;
	std::size_t upgrade_bytes = 0;
	std::size_t filtered_bytes = 0;
	std::size_t filtered_blocks = 0;
	std::size_t parsed_fields = 0;
	std::size_t button_count = 0;
	std::string source;
	std::string archive_path;
	bool flash_bang_upgrade_found = false;
	int flash_bang_upgrade_command = 0;
	int flash_bang_upgrade_border = 0;
	std::string flash_bang_upgrade_name;
	std::string flash_bang_upgrade_label;
	std::string flash_bang_upgrade_description;
	bool ranger_capture_found = false;
	int ranger_capture_command = 0;
	unsigned int ranger_capture_options = 0;
	int ranger_capture_border = 0;
	std::string ranger_capture_upgrade_name;
	std::string ranger_capture_special_power_name;
	std::string ranger_capture_label;
	std::string ranger_capture_description;
	std::string ranger_capture_cursor;
	std::string ranger_capture_invalid_cursor;
	bool ranger_capture_has_enemy_target = false;
	bool ranger_capture_has_neutral_target = false;
	bool ranger_capture_has_multi_select = false;
	bool ranger_capture_has_need_upgrade = false;
	bool ranger_capture_has_need_special_power_science = false;
	bool flash_bang_switch_found = false;
	int flash_bang_switch_command = 0;
	unsigned int flash_bang_switch_options = 0;
	int flash_bang_switch_weapon_slot = 0;
	int flash_bang_switch_border = 0;
	std::string flash_bang_switch_upgrade_name;
	std::string flash_bang_switch_label;
	std::string flash_bang_switch_description;
	bool flash_bang_switch_has_check_like = false;
	bool flash_bang_switch_has_multi_select = false;
	bool flash_bang_switch_has_need_upgrade = false;
};

struct RealCommandSetIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool command_button_file_exists = false;
	bool special_power_file_exists = false;
	bool upgrade_file_exists = false;
	bool name_key_generator_loaded = false;
	bool special_power_original_ini_load = false;
	bool upgrade_original_ini_load = false;
	bool command_button_original_ini_load = false;
	bool original_ini_load = false;
	bool filtered_from_shipped = false;
	std::size_t bytes = 0;
	std::size_t command_button_bytes = 0;
	std::size_t special_power_bytes = 0;
	std::size_t upgrade_bytes = 0;
	std::size_t filtered_command_button_bytes = 0;
	std::size_t filtered_command_button_blocks = 0;
	std::size_t filtered_command_set_bytes = 0;
	std::size_t filtered_command_set_blocks = 0;
	std::size_t parsed_fields = 0;
	std::size_t command_button_count = 0;
	std::size_t command_set_count = 0;
	std::string source;
	std::string archive_path;
	bool ranger_set_found = false;
	std::string ranger_slot1;
	std::string ranger_slot2;
	std::string ranger_slot4;
	std::string ranger_slot11;
	std::string ranger_slot13;
	std::string ranger_slot14;
	int ranger_slot1_command = 0;
	int ranger_slot2_command = 0;
	int ranger_slot4_command = 0;
	int ranger_slot11_command = 0;
	int ranger_slot13_command = 0;
	int ranger_slot14_command = 0;
	int ranger_slot2_weapon_slot = 0;
	int ranger_slot4_weapon_slot = 0;
	std::string ranger_slot1_special_power;
	std::string ranger_slot1_upgrade;
	std::string ranger_slot4_upgrade;
};

struct RealPlayerTemplateIniProbeResult
{
	bool attempted = false;
	bool ok = false;
	bool loaded_archives = false;
	bool file_exists = false;
	bool science_file_exists = false;
	bool game_text_loaded = false;
	bool name_key_generator_loaded = false;
	bool science_original_ini_load = false;
	bool original_ini_load = false;
	std::size_t bytes = 0;
	std::size_t science_bytes = 0;
	std::size_t parsed_fields = 0;
	std::size_t player_template_count = 0;
	std::size_t side_count = 0;
	std::string source;
	std::string archive_path;
	bool america_found = false;
	bool china_found = false;
	bool gla_found = false;
	bool observer_found = false;
	bool air_force_found = false;
	bool boss_found = false;
	bool america_display_name_loaded = false;
	std::string america_side;
	std::string america_base_side;
	bool america_playable = false;
	bool america_old_faction = false;
	int america_start_money = 0;
	std::size_t america_intrinsic_science_count = 0;
	bool america_intrinsic_science_valid = false;
	std::string america_starting_building;
	std::string america_starting_unit0;
	std::string america_shortcut_command_set;
	std::string america_shortcut_win_name;
	int america_shortcut_button_count = 0;
	std::string america_load_screen;
	std::string america_score_screen;
	std::string america_load_music;
	std::string america_score_music;
	std::string america_beacon;
	bool observer_is_observer = false;
	bool observer_playable = false;
	std::string observer_side;
	std::string observer_load_screen;
	std::string observer_beacon;
	std::string air_force_side;
	std::string air_force_base_side;
	bool air_force_playable = false;
	bool air_force_old_faction = false;
	std::string air_force_starting_building;
	std::string air_force_starting_unit0;
	std::string air_force_shortcut_command_set;
	int air_force_shortcut_button_count = 0;
	std::string boss_side;
	std::string boss_base_side;
	bool boss_playable = false;
	bool boss_old_faction = false;
	std::size_t boss_intrinsic_science_count = 0;
	bool boss_intrinsic_sciences_valid = false;
	std::string boss_starting_building;
	std::string boss_starting_unit0;
	std::string boss_shortcut_command_set;
	std::string boss_shortcut_win_name;
	int boss_shortcut_button_count = 0;
};

RealGameDataIniProbeResult probe_original_game_data_ini_load(const char *archive_path);
RealArmorIniProbeResult probe_original_armor_ini_load(const char *archive_path);
RealScienceIniProbeResult probe_original_science_ini_load(const char *archive_path);
RealMapCacheIniProbeResult probe_original_map_cache_ini_load(const char *archive_path);
RealWeatherIniProbeResult probe_original_weather_ini_load(const char *archive_path);
RealWaterIniProbeResult probe_original_water_ini_load(const char *archive_path);
RealVideoIniProbeResult probe_original_video_ini_load(const char *archive_path);
RealMultiplayerIniProbeResult probe_original_multiplayer_ini_load(const char *archive_path);
RealTerrainIniProbeResult probe_original_terrain_ini_load(const char *archive_path);
RealTerrainRoadsIniProbeResult probe_original_terrain_roads_ini_load(const char *archive_path);
RealDrawGroupInfoIniProbeResult probe_original_draw_group_info_ini_load(const char *archive_path);
RealUpgradeIniProbeResult probe_original_upgrade_ini_load(const char *archive_path);
RealSpecialPowerIniProbeResult probe_original_special_power_ini_load(const char *archive_path);
RealCommandButtonIniProbeResult probe_original_command_button_ini_load(const char *archive_path);
RealCommandSetIniProbeResult probe_original_command_set_ini_load(const char *archive_path);
RealPlayerTemplateIniProbeResult probe_original_player_template_ini_load(const char *archive_path);
